export type ReviewIqUiCopy = {
  stepOf: string;
  switchCustomer: string;
  stepChooseStay: string;
  stepInputStyle: string;
  stepReview: string;
  stepFollowUp: string;
  stepProfile: string;
  chooseStayHeading: string;
  checkIn: string;
  checkOut: string;
  roomType: string;
  confirmation: string;
  allStaysReviewed: string;
  emptyQueue: string;
  goToAtlasCapsule: string;
  backToCustomers: string;
  shareHeading: string;
  writeYourReview: string;
  speakYourReview: string;
  back: string;
  overallImpression: string;
  yourReview: string;
  reviewIqTip: string;
  recordReview: string;
  stopRecording: string;
  listeningNow: string;
  tapRecordAndSpeak: string;
  voiceUnavailable: string;
  transcript: string;
  reviewTranscriptPlaceholder: string;
  writePlaceholder: string;
  excellentDetail: string;
  gettingThere: string;
  keepGoing: string;
  keepTalking: string;
  keepWriting: string;
  word: string;
  words: string;
  day: string;
  days: string;
  addPhotosOptional: string;
  dragPhotos: string;
  photoUploadSub: string;
  uploadedPhotoAlt: string;
  nextPage: string;
  submitReview: string;
  submitting: string;
  adaptiveQuestions: string;
  adaptiveQuestionsCopy: string;
  skip: string;
  findingBestFollowUp: string;
  followUpLoadingText: string;
  noAdditionalQuestions: string;
  noAdditionalQuestionsBody: string;
  noAdditionalQuestionsHelper: string;
  questionOf: string;
  recordAnswer: string;
  answerListeningNow: string;
  answerIdle: string;
  answerTranscriptPlaceholder: string;
  addDetailIfSpecific: string;
  answerCaptured: string;
  travelerTasteProfile: string;
  tasteUpdated: string;
  matchedProperties: string;
  gapsClosed: string;
  reviewsSubmitted: string;
  closedGaps: string;
  freshTravelerEvidence: string;
  refreshedFromReview: string;
  whatYouShared: string;
  photos: string;
  photosUploaded: string;
  reviewAnotherProperty: string;
  footerSubtitle: string;
  footerNote: string;
  puzzleTitle: string;
  didYouKnow: string;
  puzzleFallback: string;
  doneModalAria: string;
  reviewSubmitted: string;
  reviewSubmittedBody: string;
  continueToAtlasCapsule: string;
  magicFixTyping: string;
  magicFixReady: string;
  magicFixYourVersion: string;
  magicFixEnhancedVersion: string;
  magicFixSuggestedTitle: string;
  magicFixGeneratingTitle: string;
  magicFixAddTitle: string;
  magicFixStatusLoading: string;
  magicFixStatusApplying: string;
  magicFixStatusEditable: string;
  magicFixTextareaPlaceholder: string;
  reviewSpeechIntro: string;
  followUpSpeechIntro: string;
  nudgeStart: string;
  nudgeThankYou: string;
  yes: string;
  no: string;
  notSure: string;
  propertyFactAmenities: string;
  propertyFactCheckIn: string;
  propertyFactCheckOut: string;
  propertyFactLatestReview: string;
  propertyFactRecentGuest: string;
  propertyFactRecentSlice: string;
  propertyFactTopGap: string;
  propertyFactAnotherGap: string;
  tasteInsight: string;
  recommendationLeader: string;
  recommendationRunnerUp: string;
  recommendationFresh: string;
  tasteValue: string;
  tasteValueArchetype: string;
  tasteLocation: string;
  tasteLocationArchetype: string;
  tasteComfort: string;
  tasteComfortArchetype: string;
  tasteService: string;
  tasteServiceArchetype: string;
  tasteAmenities: string;
  tasteAmenitiesArchetype: string;
  stampediaCapsule: string;
  travelCapsule: string;
  travelCapsuleSub: string;
  dateRange: string;
  duration: string;
  country: string;
  stamped: string;
  stampediaPage: string;
  closeReviewPreview: string;
  savedReview: string;
  noStampsYetNote: string;
  newStampNote: string;
  stampsCollectedNote: string;
  openSavedReviewAria: string;
  atlasCapsuleJournal: string;
  noStampsYetCountry: string;
  firstReviewSubtitle: string;
  countryJournal: string;
  recentStay: string;
  qualityLabel: string;
};

export type MagicFixCopy = {
  title: string;
  body: string;
  accept: string;
  keep: string;
  loading: string;
};

function replaceTokens(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""));
}

const UI_COPY_BY_LANGUAGE: Record<string, ReviewIqUiCopy> = {
  en: {
    stepOf: "Step {current} of {total}",
    switchCustomer: "Switch customer",
    stepChooseStay: "Choose Stay",
    stepInputStyle: "Input Style",
    stepReview: "Review",
    stepFollowUp: "Follow-up",
    stepProfile: "Profile",
    chooseStayHeading: "Hi, {name}! Choose one of your recent stays to review.",
    checkIn: "Check-in",
    checkOut: "Check-out",
    roomType: "Room type",
    confirmation: "Confirmation",
    allStaysReviewed: "All stays reviewed",
    emptyQueue: "{name}'s review queue is empty. The rest of the journey now lives in Atlas Capsule.",
    goToAtlasCapsule: "Go to Atlas Capsule",
    backToCustomers: "Back to customers",
    shareHeading: "How would you like to share, {name}?",
    writeYourReview: "Write your review",
    speakYourReview: "Speak your review",
    back: "Back",
    overallImpression: "Overall impression",
    yourReview: "Your review",
    reviewIqTip: "Atlas Pro Tip",
    recordReview: "Record review",
    stopRecording: "Stop recording",
    listeningNow: "Listening now. Speak naturally and the transcript will appear below.",
    tapRecordAndSpeak: "Tap record and speak your review out loud. You can also edit the transcript below.",
    voiceUnavailable: "Voice input is not available in this browser.",
    transcript: "Transcript",
    reviewTranscriptPlaceholder: "Your recorded review will appear here as you speak.",
    writePlaceholder: "What stood out most about your stay? Start anywhere.",
    excellentDetail: "Excellent detail",
    gettingThere: "Getting there",
    keepGoing: "Keep going",
    keepTalking: "Keep talking",
    keepWriting: "Keep writing",
    word: "word",
    words: "words",
    day: "day",
    days: "days",
    addPhotosOptional: "Add photos (optional)",
    dragPhotos: "Drag photos here or click to upload",
    photoUploadSub: "JPG, PNG or HEIC.",
    uploadedPhotoAlt: "Uploaded property evidence",
    nextPage: "Next page",
    submitReview: "Submit review",
    submitting: "Submitting...",
    adaptiveQuestions: "Adaptive questions",
    adaptiveQuestionsCopy: "Answer the last 1-2 gaps, or skip if you don't want to add more.",
    skip: "Skip",
    findingBestFollowUp: "Finding the best follow-up",
    followUpLoadingText: "Looking at missing, stale, and conflicting property details to decide what still matters most.",
    noAdditionalQuestions: "No additional questions",
    noAdditionalQuestionsBody: "Your review already closed the highest-value gaps for this property.",
    noAdditionalQuestionsHelper: "You can submit from here without answering anything else.",
    questionOf: "Question {current} of {total} • {label}",
    recordAnswer: "Record answer",
    answerListeningNow: "Listening now. Speak your answer and the transcript will appear below.",
    answerIdle: "Click Record answer when you are ready. You can edit the transcript below if needed.",
    answerTranscriptPlaceholder: "Your recorded answer will appear here as you speak.",
    addDetailIfSpecific: "Add a little detail if you noticed anything specific.",
    answerCaptured: "Answer captured. You can still edit it before submitting.",
    travelerTasteProfile: "Traveler Taste Profile",
    tasteUpdated: "Updated after this review. Recalculates with every stay.",
    matchedProperties: "Matched properties for your next trip",
    gapsClosed: "Gaps closed",
    reviewsSubmitted: "Reviews submitted",
    closedGaps: "Closed gaps",
    freshTravelerEvidence: "Fresh traveler evidence",
    refreshedFromReview: "{labels} refreshed from this review.",
    whatYouShared: "What you shared",
    photos: "Photos",
    photosUploaded: "{count} photos uploaded",
    reviewAnotherProperty: "Review another property",
    footerSubtitle: "Helping Expedia collect sharper, fresher travel reviews.",
    footerNote: "Built for Expedia travel feedback experiences.",
    puzzleTitle: "Reveal the property",
    didYouKnow: "Did you know?",
    puzzleFallback: "Answer questions to reveal pieces and unlock property facts.",
    doneModalAria: "Close review submitted",
    reviewSubmitted: "Review submitted",
    reviewSubmittedBody: "Your review is in. Continue to Atlas Capsule to see your new stamp arrive.",
    continueToAtlasCapsule: "Continue to Atlas Capsule",
    magicFixTyping: "We are typing in the grammar, spelling, punctuation, and capitalization fixes now. You can edit the enhanced version once it finishes.",
    magicFixReady: "You can watch the fixes appear, then accept or decline them.",
    magicFixYourVersion: "Your version",
    magicFixEnhancedVersion: "Enhanced version",
    magicFixSuggestedTitle: "Suggested title",
    magicFixGeneratingTitle: "Generating a title...",
    magicFixAddTitle: "Add a title",
    magicFixStatusLoading: "OpenAI is enhancing your review and generating a title...",
    magicFixStatusApplying: "Applying fixes...",
    magicFixStatusEditable: "You can edit the title and review before accepting.",
    magicFixTextareaPlaceholder: "Enhancing your review...",
    reviewSpeechIntro: "Tell me about your stay at {property}. When you are ready, click Record review to start speaking.",
    followUpSpeechIntro: "Smart follow-up. {prompt}.",
    nudgeStart: "Start with what stood out most: the room, the staff, the location, or the overall feel.",
    nudgeThankYou: "Thank you for your valuable input!",
    yes: "Yes",
    no: "No",
    notSure: "Not sure",
    propertyFactAmenities: "Travelers most often mention {items} here.",
    propertyFactCheckIn: "Current listing says check-in runs {value}.",
    propertyFactCheckOut: "Check-out is listed as {value}.",
    propertyFactLatestReview: "The latest review in the dataset was captured on {date}.",
    propertyFactRecentGuest: "A recent guest said: {summary}",
    propertyFactRecentSlice: "{count} reviews in the recent slice help ground the follow-up question.",
    propertyFactTopGap: "One of the highest-value info gaps is {label}.",
    propertyFactAnotherGap: "Another likely stale topic is {label}.",
    tasteInsight: "Your answers leaned hardest toward {leader}, with {runnerUp} close behind. That profile is exactly the kind of signal a travel platform can use to personalize future ranking and highlight the facts you care about most.",
    recommendationLeader: "{leader}-forward stays",
    recommendationRunnerUp: "Top-rated {runnerUp} picks",
    recommendationFresh: "Freshly updated listings",
    tasteValue: "Value",
    tasteValueArchetype: "Optimizer",
    tasteLocation: "Location",
    tasteLocationArchetype: "Seeker",
    tasteComfort: "Comfort",
    tasteComfortArchetype: "Nester",
    tasteService: "Service",
    tasteServiceArchetype: "Loyalist",
    tasteAmenities: "Amenities",
    tasteAmenitiesArchetype: "Indulger",
    stampediaCapsule: "Capsule",
    travelCapsule: "{name}'s travel capsule",
    travelCapsuleSub: "Reviewed stays, saved as keepsakes",
    dateRange: "Date range",
    duration: "Duration",
    country: "Country",
    stamped: "Stamped",
    stampediaPage: "Page {page}",
    closeReviewPreview: "Close review preview",
    savedReview: "Saved review",
    noStampsYetNote: "No stamps yet. Submit the first review in {title} to start this journal.",
    newStampNote: "{property} just slid into your {title} spread.",
    stampsCollectedNote: "{count} collected for {country}.",
    openSavedReviewAria: "Open saved review for {property}",
    atlasCapsuleJournal: "Atlas Capsule Journal",
    noStampsYetCountry: "No stamps yet",
    firstReviewSubtitle: "Submit your first review to start collecting stamps.",
    countryJournal: "{country} Journal",
    recentStay: "Recent trip",
    qualityLabel: "{count} recent stays"
  },
  es: {
    stepOf: "Paso {current} de {total}",
    switchCustomer: "Cambiar cliente",
    stepChooseStay: "Elegir estadía",
    stepInputStyle: "Modo de entrada",
    stepReview: "Reseña",
    stepFollowUp: "Seguimiento",
    stepProfile: "Perfil",
    chooseStayHeading: "Hola, {name}. Elige una de tus estadías recientes para reseñarla.",
    checkIn: "Entrada",
    checkOut: "Salida",
    roomType: "Tipo de habitación",
    confirmation: "Confirmación",
    allStaysReviewed: "Todas las estadías reseñadas",
    emptyQueue: "La cola de reseñas de {name} está vacía. El resto del recorrido ahora vive en Atlas Capsule.",
    goToAtlasCapsule: "Ir a Atlas Capsule",
    backToCustomers: "Volver a clientes",
    shareHeading: "¿Cómo te gustaría compartir, {name}?",
    writeYourReview: "Escribir tu reseña",
    speakYourReview: "Decir tu reseña",
    back: "Volver",
    overallImpression: "Impresión general",
    yourReview: "Tu reseña",
    reviewIqTip: "Atlas Pro Tip",
    recordReview: "Grabar reseña",
    stopRecording: "Detener grabación",
    listeningNow: "Escuchando. Habla con naturalidad y la transcripción aparecerá abajo.",
    tapRecordAndSpeak: "Toca grabar y cuenta tu reseña en voz alta. También puedes editar la transcripción abajo.",
    voiceUnavailable: "La entrada por voz no está disponible en este navegador.",
    transcript: "Transcripción",
    reviewTranscriptPlaceholder: "Tu reseña grabada aparecerá aquí mientras hablas.",
    writePlaceholder: "¿Qué fue lo que más destacó de tu estadía? Empieza donde quieras.",
    excellentDetail: "Excelente detalle",
    gettingThere: "Vas bien",
    keepGoing: "Sigue así",
    keepTalking: "Sigue hablando",
    keepWriting: "Sigue escribiendo",
    word: "palabra",
    words: "palabras",
    day: "día",
    days: "días",
    addPhotosOptional: "Agregar fotos (opcional)",
    dragPhotos: "Arrastra fotos aquí o haz clic para subirlas",
    photoUploadSub: "JPG, PNG o HEIC.",
    uploadedPhotoAlt: "Evidencia subida de la propiedad",
    nextPage: "Página siguiente",
    submitReview: "Enviar reseña",
    submitting: "Enviando...",
    adaptiveQuestions: "Preguntas adaptativas",
    adaptiveQuestionsCopy: "Responde las últimas 1 o 2 brechas, o salta si no quieres agregar más.",
    skip: "Saltar",
    findingBestFollowUp: "Buscando el mejor seguimiento",
    followUpLoadingText: "Revisando detalles faltantes, desactualizados y contradictorios para decidir qué sigue importando más.",
    noAdditionalQuestions: "Sin preguntas adicionales",
    noAdditionalQuestionsBody: "Tu reseña ya cerró las brechas de mayor valor para esta propiedad.",
    noAdditionalQuestionsHelper: "Puedes enviarla desde aquí sin responder nada más.",
    questionOf: "Pregunta {current} de {total} • {label}",
    recordAnswer: "Grabar respuesta",
    answerListeningNow: "Escuchando. Di tu respuesta y la transcripción aparecerá abajo.",
    answerIdle: "Haz clic en Grabar respuesta cuando estés listo. Puedes editar la transcripción abajo si hace falta.",
    answerTranscriptPlaceholder: "Tu respuesta grabada aparecerá aquí mientras hablas.",
    addDetailIfSpecific: "Agrega un poco más de detalle si notaste algo específico.",
    answerCaptured: "Respuesta guardada. Aún puedes editarla antes de enviarla.",
    travelerTasteProfile: "Perfil de gustos del viajero",
    tasteUpdated: "Actualizado después de esta reseña. Se recalcula con cada estadía.",
    matchedProperties: "Propiedades sugeridas para tu próximo viaje",
    gapsClosed: "Brechas cerradas",
    reviewsSubmitted: "Reseñas enviadas",
    closedGaps: "Brechas cerradas",
    freshTravelerEvidence: "Evidencia fresca del viajero",
    refreshedFromReview: "{labels} se actualizó con esta reseña.",
    whatYouShared: "Lo que compartiste",
    photos: "Fotos",
    photosUploaded: "{count} fotos subidas",
    reviewAnotherProperty: "Reseñar otra propiedad",
    footerSubtitle: "Ayudando a Expedia a recopilar reseñas de viaje más precisas y recientes.",
    footerNote: "Creado para experiencias de comentarios de viaje de Expedia.",
    puzzleTitle: "Revela la propiedad",
    didYouKnow: "¿Sabías que?",
    puzzleFallback: "Responde preguntas para revelar piezas y desbloquear datos de la propiedad.",
    doneModalAria: "Cerrar reseña enviada",
    reviewSubmitted: "Reseña enviada",
    reviewSubmittedBody: "Tu reseña ya está lista. Continúa a Atlas Capsule para ver llegar tu nuevo sello.",
    continueToAtlasCapsule: "Continuar a Atlas Capsule",
    magicFixTyping: "Ahora estamos escribiendo las correcciones de gramática, ortografía, puntuación y mayúsculas. Podrás editar la versión mejorada cuando termine.",
    magicFixReady: "Puedes ver aparecer los cambios y luego aceptarlos o rechazarlos.",
    magicFixYourVersion: "Tu versión",
    magicFixEnhancedVersion: "Versión mejorada",
    magicFixSuggestedTitle: "Título sugerido",
    magicFixGeneratingTitle: "Generando un título...",
    magicFixAddTitle: "Agregar un título",
    magicFixStatusLoading: "OpenAI está mejorando tu reseña y generando un título...",
    magicFixStatusApplying: "Aplicando correcciones...",
    magicFixStatusEditable: "Puedes editar el título y la reseña antes de aceptar.",
    magicFixTextareaPlaceholder: "Mejorando tu reseña...",
    reviewSpeechIntro: "Cuéntame sobre tu estadía en {property}. Cuando estés listo, haz clic en Grabar reseña para empezar a hablar.",
    followUpSpeechIntro: "Seguimiento inteligente. {prompt}.",
    nudgeStart: "Empieza por lo que más destacó: la habitación, el personal, la ubicación o la sensación general.",
    nudgeThankYou: "Gracias por tu valioso aporte.",
    yes: "Sí",
    no: "No",
    notSure: "No estoy seguro",
    propertyFactAmenities: "Los viajeros suelen mencionar aquí {items}.",
    propertyFactCheckIn: "La ficha actual indica que el check-in es {value}.",
    propertyFactCheckOut: "La salida figura como {value}.",
    propertyFactLatestReview: "La reseña más reciente del conjunto de datos se registró el {date}.",
    propertyFactRecentGuest: "Un huésped reciente dijo: {summary}",
    propertyFactRecentSlice: "{count} reseñas recientes ayudan a fundamentar la pregunta de seguimiento.",
    propertyFactTopGap: "Una de las brechas de información más valiosas es {label}.",
    propertyFactAnotherGap: "Otro tema que probablemente esté desactualizado es {label}.",
    tasteInsight: "Tus respuestas se inclinaron más por {leader}, con {runnerUp} muy cerca. Ese perfil es exactamente el tipo de señal que una plataforma de viajes puede usar para personalizar futuros rankings y resaltar los datos que más te importan.",
    recommendationLeader: "Estadías enfocadas en {leader}",
    recommendationRunnerUp: "Opciones destacadas de {runnerUp}",
    recommendationFresh: "Listados actualizados recientemente",
    tasteValue: "Valor",
    tasteValueArchetype: "Optimizador",
    tasteLocation: "Ubicación",
    tasteLocationArchetype: "Explorador",
    tasteComfort: "Comodidad",
    tasteComfortArchetype: "Hogareño",
    tasteService: "Servicio",
    tasteServiceArchetype: "Leal",
    tasteAmenities: "Servicios",
    tasteAmenitiesArchetype: "Disfrutador",
    stampediaCapsule: "Capsule",
    travelCapsule: "Cápsula de viaje de {name}",
    travelCapsuleSub: "Estadías reseñadas, guardadas como recuerdos",
    dateRange: "Rango de fechas",
    duration: "Duración",
    country: "País",
    stamped: "Sellado",
    stampediaPage: "Página {page}",
    closeReviewPreview: "Cerrar vista previa de reseña",
    savedReview: "Reseña guardada",
    noStampsYetNote: "Todavía no hay sellos. Envía la primera reseña de {title} para comenzar este diario.",
    newStampNote: "{property} acaba de entrar en tu página de {title}.",
    stampsCollectedNote: "{count} reunidos para {country}.",
    openSavedReviewAria: "Abrir reseña guardada de {property}",
    atlasCapsuleJournal: "Diario Atlas Capsule",
    noStampsYetCountry: "Aún sin sellos",
    firstReviewSubtitle: "Envía tu primera reseña para empezar a coleccionar sellos.",
    countryJournal: "Diario de {country}",
    recentStay: "Viaje reciente",
    qualityLabel: "{count} estadías recientes"
  },
  fr: {
    stepOf: "Étape {current} sur {total}",
    switchCustomer: "Changer de client",
    stepChooseStay: "Choisir le séjour",
    stepInputStyle: "Mode de saisie",
    stepReview: "Avis",
    stepFollowUp: "Suivi",
    stepProfile: "Profil",
    chooseStayHeading: "Bonjour, {name}. Choisissez l’un de vos séjours récents à évaluer.",
    checkIn: "Arrivée",
    checkOut: "Départ",
    roomType: "Type de chambre",
    confirmation: "Confirmation",
    allStaysReviewed: "Tous les séjours sont évalués",
    emptyQueue: "La file d’avis de {name} est vide. Le reste du parcours vit maintenant dans Atlas Capsule.",
    goToAtlasCapsule: "Aller à Atlas Capsule",
    backToCustomers: "Retour aux clients",
    shareHeading: "Comment souhaitez-vous partager, {name} ?",
    writeYourReview: "Écrire votre avis",
    speakYourReview: "Dire votre avis",
    back: "Retour",
    overallImpression: "Impression générale",
    yourReview: "Votre avis",
    reviewIqTip: "Atlas Pro Tip",
    recordReview: "Enregistrer l’avis",
    stopRecording: "Arrêter l’enregistrement",
    listeningNow: "Écoute en cours. Parlez naturellement et la transcription apparaîtra ci-dessous.",
    tapRecordAndSpeak: "Appuyez sur enregistrer et dites votre avis à voix haute. Vous pouvez aussi modifier la transcription ci-dessous.",
    voiceUnavailable: "La saisie vocale n’est pas disponible dans ce navigateur.",
    transcript: "Transcription",
    reviewTranscriptPlaceholder: "Votre avis enregistré apparaîtra ici pendant que vous parlez.",
    writePlaceholder: "Qu’est-ce qui vous a le plus marqué pendant votre séjour ? Commencez où vous voulez.",
    excellentDetail: "Excellent niveau de détail",
    gettingThere: "Vous y êtes presque",
    keepGoing: "Continuez",
    keepTalking: "Continuez à parler",
    keepWriting: "Continuez à écrire",
    word: "mot",
    words: "mots",
    day: "jour",
    days: "jours",
    addPhotosOptional: "Ajouter des photos (facultatif)",
    dragPhotos: "Glissez des photos ici ou cliquez pour les importer",
    photoUploadSub: "JPG, PNG ou HEIC.",
    uploadedPhotoAlt: "Preuve visuelle importée de l’établissement",
    nextPage: "Page suivante",
    submitReview: "Envoyer l’avis",
    submitting: "Envoi...",
    adaptiveQuestions: "Questions adaptatives",
    adaptiveQuestionsCopy: "Répondez aux 1 ou 2 derniers points manquants, ou passez si vous ne voulez rien ajouter.",
    skip: "Passer",
    findingBestFollowUp: "Recherche du meilleur suivi",
    followUpLoadingText: "Analyse des détails manquants, anciens et contradictoires pour voir ce qui compte encore le plus.",
    noAdditionalQuestions: "Aucune question supplémentaire",
    noAdditionalQuestionsBody: "Votre avis a déjà couvert les points les plus importants pour cet établissement.",
    noAdditionalQuestionsHelper: "Vous pouvez envoyer depuis ici sans rien ajouter.",
    questionOf: "Question {current} sur {total} • {label}",
    recordAnswer: "Enregistrer la réponse",
    answerListeningNow: "Écoute en cours. Dites votre réponse et la transcription apparaîtra ci-dessous.",
    answerIdle: "Cliquez sur Enregistrer la réponse quand vous êtes prêt. Vous pouvez modifier la transcription si besoin.",
    answerTranscriptPlaceholder: "Votre réponse enregistrée apparaîtra ici pendant que vous parlez.",
    addDetailIfSpecific: "Ajoutez un peu de détail si vous avez remarqué quelque chose de précis.",
    answerCaptured: "Réponse enregistrée. Vous pouvez encore la modifier avant l’envoi.",
    travelerTasteProfile: "Profil de goût du voyageur",
    tasteUpdated: "Mis à jour après cet avis. Recalculé à chaque séjour.",
    matchedProperties: "Établissements recommandés pour votre prochain voyage",
    gapsClosed: "Points comblés",
    reviewsSubmitted: "Avis envoyés",
    closedGaps: "Points comblés",
    freshTravelerEvidence: "Nouveaux signaux voyageurs",
    refreshedFromReview: "{labels} a été rafraîchi à partir de cet avis.",
    whatYouShared: "Ce que vous avez partagé",
    photos: "Photos",
    photosUploaded: "{count} photos importées",
    reviewAnotherProperty: "Évaluer un autre établissement",
    footerSubtitle: "Aider Expedia à collecter des avis de voyage plus précis et plus récents.",
    footerNote: "Conçu pour les expériences de retour voyage d’Expedia.",
    puzzleTitle: "Révéler l’établissement",
    didYouKnow: "Le saviez-vous ?",
    puzzleFallback: "Répondez aux questions pour révéler des pièces et débloquer des informations sur l’établissement.",
    doneModalAria: "Fermer l’avis envoyé",
    reviewSubmitted: "Avis envoyé",
    reviewSubmittedBody: "Votre avis est enregistré. Continuez vers Atlas Capsule pour voir arriver votre nouveau tampon.",
    continueToAtlasCapsule: "Continuer vers Atlas Capsule",
    magicFixTyping: "Nous écrivons maintenant les corrections de grammaire, d’orthographe, de ponctuation et de majuscules. Vous pourrez modifier la version améliorée ensuite.",
    magicFixReady: "Vous pouvez regarder les corrections apparaître, puis les accepter ou les refuser.",
    magicFixYourVersion: "Votre version",
    magicFixEnhancedVersion: "Version améliorée",
    magicFixSuggestedTitle: "Titre suggéré",
    magicFixGeneratingTitle: "Génération d’un titre...",
    magicFixAddTitle: "Ajouter un titre",
    magicFixStatusLoading: "OpenAI améliore votre avis et génère un titre...",
    magicFixStatusApplying: "Application des corrections...",
    magicFixStatusEditable: "Vous pouvez modifier le titre et l’avis avant d’accepter.",
    magicFixTextareaPlaceholder: "Amélioration de votre avis...",
    reviewSpeechIntro: "Parlez-moi de votre séjour à {property}. Quand vous êtes prêt, cliquez sur Enregistrer l’avis pour commencer à parler.",
    followUpSpeechIntro: "Suivi intelligent. {prompt}.",
    nudgeStart: "Commencez par ce qui vous a le plus marqué : la chambre, le personnel, l’emplacement ou l’impression générale.",
    nudgeThankYou: "Merci pour votre contribution précieuse.",
    yes: "Oui",
    no: "Non",
    notSure: "Pas sûr",
    propertyFactAmenities: "Les voyageurs mentionnent le plus souvent {items} ici.",
    propertyFactCheckIn: "L’annonce actuelle indique un enregistrement {value}.",
    propertyFactCheckOut: "Le départ est indiqué à {value}.",
    propertyFactLatestReview: "L’avis le plus récent du jeu de données date du {date}.",
    propertyFactRecentGuest: "Un voyageur récent a dit : {summary}",
    propertyFactRecentSlice: "{count} avis récents servent à cadrer la question de suivi.",
    propertyFactTopGap: "L’un des manques d’information les plus importants concerne {label}.",
    propertyFactAnotherGap: "Un autre sujet probablement ancien est {label}.",
    tasteInsight: "Vos réponses ont surtout penché vers {leader}, avec {runnerUp} juste derrière. C’est exactement le type de signal qu’une plateforme de voyage peut utiliser pour personnaliser les futurs classements et mettre en avant les informations qui comptent le plus pour vous.",
    recommendationLeader: "Séjours centrés sur {leader}",
    recommendationRunnerUp: "Meilleurs choix pour {runnerUp}",
    recommendationFresh: "Annonces fraîchement mises à jour",
    tasteValue: "Valeur",
    tasteValueArchetype: "Optimisateur",
    tasteLocation: "Emplacement",
    tasteLocationArchetype: "Explorateur",
    tasteComfort: "Confort",
    tasteComfortArchetype: "Cocoon",
    tasteService: "Service",
    tasteServiceArchetype: "Fidèle",
    tasteAmenities: "Équipements",
    tasteAmenitiesArchetype: "Épicurien",
    stampediaCapsule: "Capsule",
    travelCapsule: "Capsule de voyage de {name}",
    travelCapsuleSub: "Séjours évalués, gardés comme souvenirs",
    dateRange: "Période",
    duration: "Durée",
    country: "Pays",
    stamped: "Tamponné",
    stampediaPage: "Page {page}",
    closeReviewPreview: "Fermer l’aperçu de l’avis",
    savedReview: "Avis enregistré",
    noStampsYetNote: "Aucun tampon pour l’instant. Envoyez le premier avis de {title} pour commencer ce journal.",
    newStampNote: "{property} vient de se glisser dans votre page {title}.",
    stampsCollectedNote: "{count} collectés pour {country}.",
    openSavedReviewAria: "Ouvrir l’avis enregistré pour {property}",
    atlasCapsuleJournal: "Journal Atlas Capsule",
    noStampsYetCountry: "Pas encore de tampons",
    firstReviewSubtitle: "Envoyez votre premier avis pour commencer à collectionner les tampons.",
    countryJournal: "Journal {country}",
    recentStay: "Voyage récent",
    qualityLabel: "{count} séjours récents"
  },
  de: {
    stepOf: "Schritt {current} von {total}",
    switchCustomer: "Kunden wechseln",
    stepChooseStay: "Aufenthalt wählen",
    stepInputStyle: "Eingabeart",
    stepReview: "Bewertung",
    stepFollowUp: "Nachfrage",
    stepProfile: "Profil",
    chooseStayHeading: "Hallo, {name}. Wähle einen deiner letzten Aufenthalte zur Bewertung aus.",
    checkIn: "Check-in",
    checkOut: "Check-out",
    roomType: "Zimmertyp",
    confirmation: "Bestätigung",
    allStaysReviewed: "Alle Aufenthalte bewertet",
    emptyQueue: "Die Bewertungswarteschlange von {name} ist leer. Der Rest der Reise lebt jetzt in Atlas Capsule.",
    goToAtlasCapsule: "Zu Atlas Capsule",
    backToCustomers: "Zurück zu Kunden",
    shareHeading: "Wie möchtest du teilen, {name}?",
    writeYourReview: "Bewertung schreiben",
    speakYourReview: "Bewertung sprechen",
    back: "Zurück",
    overallImpression: "Gesamteindruck",
    yourReview: "Deine Bewertung",
    reviewIqTip: "Atlas Pro Tip",
    recordReview: "Bewertung aufnehmen",
    stopRecording: "Aufnahme stoppen",
    listeningNow: "Ich höre zu. Sprich natürlich, die Abschrift erscheint unten.",
    tapRecordAndSpeak: "Tippe auf Aufnahme und sprich deine Bewertung laut aus. Du kannst die Abschrift unten auch bearbeiten.",
    voiceUnavailable: "Spracheingabe ist in diesem Browser nicht verfügbar.",
    transcript: "Transkript",
    reviewTranscriptPlaceholder: "Deine aufgenommene Bewertung erscheint hier, während du sprichst.",
    writePlaceholder: "Was ist dir an deinem Aufenthalt am meisten aufgefallen? Fang irgendwo an.",
    excellentDetail: "Sehr detailliert",
    gettingThere: "Fast geschafft",
    keepGoing: "Weiter so",
    keepTalking: "Weiter sprechen",
    keepWriting: "Weiter schreiben",
    word: "Wort",
    words: "Wörter",
    day: "Tag",
    days: "Tage",
    addPhotosOptional: "Fotos hinzufügen (optional)",
    dragPhotos: "Fotos hierher ziehen oder zum Hochladen klicken",
    photoUploadSub: "JPG, PNG oder HEIC.",
    uploadedPhotoAlt: "Hochgeladener Nachweis zur Unterkunft",
    nextPage: "Nächste Seite",
    submitReview: "Bewertung absenden",
    submitting: "Wird gesendet...",
    adaptiveQuestions: "Adaptive Fragen",
    adaptiveQuestionsCopy: "Beantworte die letzten 1 bis 2 Lücken oder überspringe sie, wenn du nichts mehr hinzufügen möchtest.",
    skip: "Überspringen",
    findingBestFollowUp: "Beste Nachfrage wird gesucht",
    followUpLoadingText: "Fehlende, veraltete und widersprüchliche Details werden geprüft, um das Wichtigste zu finden.",
    noAdditionalQuestions: "Keine weiteren Fragen",
    noAdditionalQuestionsBody: "Deine Bewertung hat die wichtigsten Lücken für diese Unterkunft bereits geschlossen.",
    noAdditionalQuestionsHelper: "Du kannst von hier aus absenden, ohne noch etwas zu beantworten.",
    questionOf: "Frage {current} von {total} • {label}",
    recordAnswer: "Antwort aufnehmen",
    answerListeningNow: "Ich höre zu. Sprich deine Antwort, die Abschrift erscheint unten.",
    answerIdle: "Klicke auf Antwort aufnehmen, wenn du bereit bist. Du kannst die Abschrift bei Bedarf unten bearbeiten.",
    answerTranscriptPlaceholder: "Deine aufgenommene Antwort erscheint hier, während du sprichst.",
    addDetailIfSpecific: "Füge gern noch ein Detail hinzu, wenn dir etwas Konkretes aufgefallen ist.",
    answerCaptured: "Antwort erfasst. Du kannst sie vor dem Absenden noch bearbeiten.",
    travelerTasteProfile: "Reisegeschmacksprofil",
    tasteUpdated: "Nach dieser Bewertung aktualisiert. Wird mit jedem Aufenthalt neu berechnet.",
    matchedProperties: "Passende Unterkünfte für deine nächste Reise",
    gapsClosed: "Lücken geschlossen",
    reviewsSubmitted: "Bewertungen gesendet",
    closedGaps: "Geschlossene Lücken",
    freshTravelerEvidence: "Frische Reisesignale",
    refreshedFromReview: "{labels} wurde durch diese Bewertung aktualisiert.",
    whatYouShared: "Was du geteilt hast",
    photos: "Fotos",
    photosUploaded: "{count} Fotos hochgeladen",
    reviewAnotherProperty: "Weitere Unterkunft bewerten",
    footerSubtitle: "Hilft Expedia, schärfere und aktuellere Reisebewertungen zu sammeln.",
    footerNote: "Entwickelt für Expedia-Reisefeedback.",
    puzzleTitle: "Unterkunft enthüllen",
    didYouKnow: "Schon gewusst?",
    puzzleFallback: "Beantworte Fragen, um Felder aufzudecken und Fakten zur Unterkunft freizuschalten.",
    doneModalAria: "Gesendete Bewertung schließen",
    reviewSubmitted: "Bewertung gesendet",
    reviewSubmittedBody: "Deine Bewertung ist drin. Gehe weiter zu Atlas Capsule, um deinen neuen Stempel zu sehen.",
    continueToAtlasCapsule: "Weiter zu Atlas Capsule",
    magicFixTyping: "Wir tragen jetzt Korrekturen für Grammatik, Rechtschreibung, Zeichensetzung und Großschreibung ein. Danach kannst du die verbesserte Version bearbeiten.",
    magicFixReady: "Du kannst die Änderungen beim Erscheinen beobachten und sie dann annehmen oder ablehnen.",
    magicFixYourVersion: "Deine Version",
    magicFixEnhancedVersion: "Verbesserte Version",
    magicFixSuggestedTitle: "Vorgeschlagener Titel",
    magicFixGeneratingTitle: "Titel wird erstellt...",
    magicFixAddTitle: "Titel hinzufügen",
    magicFixStatusLoading: "OpenAI verbessert deine Bewertung und erstellt einen Titel...",
    magicFixStatusApplying: "Korrekturen werden angewendet...",
    magicFixStatusEditable: "Du kannst Titel und Bewertung vor dem Annehmen bearbeiten.",
    magicFixTextareaPlaceholder: "Deine Bewertung wird verbessert...",
    reviewSpeechIntro: "Erzähl mir von deinem Aufenthalt im {property}. Wenn du bereit bist, klicke auf Bewertung aufnehmen, um zu sprechen.",
    followUpSpeechIntro: "Intelligente Nachfrage. {prompt}.",
    nudgeStart: "Beginne mit dem, was am meisten aufgefallen ist: das Zimmer, das Personal, die Lage oder der Gesamteindruck.",
    nudgeThankYou: "Danke für deinen wertvollen Beitrag.",
    yes: "Ja",
    no: "Nein",
    notSure: "Nicht sicher",
    propertyFactAmenities: "Reisende erwähnen hier am häufigsten {items}.",
    propertyFactCheckIn: "Im aktuellen Eintrag steht, dass der Check-in {value} ist.",
    propertyFactCheckOut: "Der Check-out ist mit {value} angegeben.",
    propertyFactLatestReview: "Die neueste Bewertung im Datensatz wurde am {date} erfasst.",
    propertyFactRecentGuest: "Ein aktueller Gast sagte: {summary}",
    propertyFactRecentSlice: "{count} Bewertungen im jüngsten Ausschnitt stützen die Nachfragefrage.",
    propertyFactTopGap: "Eine der wertvollsten Informationslücken betrifft {label}.",
    propertyFactAnotherGap: "Ein weiteres wahrscheinlich veraltetes Thema ist {label}.",
    tasteInsight: "Deine Antworten haben am stärksten in Richtung {leader} tendiert, dicht gefolgt von {runnerUp}. Genau solche Signale kann eine Reiseplattform nutzen, um künftige Rankings zu personalisieren und die für dich wichtigsten Fakten hervorzuheben.",
    recommendationLeader: "Aufenthalte mit Fokus auf {leader}",
    recommendationRunnerUp: "Top-Auswahl für {runnerUp}",
    recommendationFresh: "Frisch aktualisierte Einträge",
    tasteValue: "Preis-Leistung",
    tasteValueArchetype: "Optimierer",
    tasteLocation: "Lage",
    tasteLocationArchetype: "Entdecker",
    tasteComfort: "Komfort",
    tasteComfortArchetype: "Nestbauer",
    tasteService: "Service",
    tasteServiceArchetype: "Loyalist",
    tasteAmenities: "Ausstattung",
    tasteAmenitiesArchetype: "Genießer",
    stampediaCapsule: "Capsule",
    travelCapsule: "{name}s Reisekapsel",
    travelCapsuleSub: "Bewertete Aufenthalte, als Erinnerungen gesichert",
    dateRange: "Zeitraum",
    duration: "Dauer",
    country: "Land",
    stamped: "Gestempelt",
    stampediaPage: "Seite {page}",
    closeReviewPreview: "Bewertungsvorschau schließen",
    savedReview: "Gespeicherte Bewertung",
    noStampsYetNote: "Noch keine Stempel. Sende die erste Bewertung in {title}, um dieses Journal zu starten.",
    newStampNote: "{property} ist gerade in deine {title}-Seite gerutscht.",
    stampsCollectedNote: "{count} gesammelt für {country}.",
    openSavedReviewAria: "Gespeicherte Bewertung für {property} öffnen",
    atlasCapsuleJournal: "Atlas Capsule Journal",
    noStampsYetCountry: "Noch keine Stempel",
    firstReviewSubtitle: "Sende deine erste Bewertung, um Stempel zu sammeln.",
    countryJournal: "{country}-Journal",
    recentStay: "Letzte Reise",
    qualityLabel: "{count} letzte Aufenthalte"
  },
  it: {
    stepOf: "Passo {current} di {total}",
    switchCustomer: "Cambia cliente",
    stepChooseStay: "Scegli il soggiorno",
    stepInputStyle: "Modalità di input",
    stepReview: "Recensione",
    stepFollowUp: "Follow-up",
    stepProfile: "Profilo",
    chooseStayHeading: "Ciao, {name}. Scegli uno dei tuoi soggiorni recenti da recensire.",
    checkIn: "Check-in",
    checkOut: "Check-out",
    roomType: "Tipo di camera",
    confirmation: "Conferma",
    allStaysReviewed: "Tutti i soggiorni recensiti",
    emptyQueue: "La coda recensioni di {name} è vuota. Il resto del percorso ora vive in Atlas Capsule.",
    goToAtlasCapsule: "Vai ad Atlas Capsule",
    backToCustomers: "Torna ai clienti",
    shareHeading: "Come vuoi condividere, {name}?",
    writeYourReview: "Scrivi la recensione",
    speakYourReview: "Parla della recensione",
    back: "Indietro",
    overallImpression: "Impressione generale",
    yourReview: "La tua recensione",
    reviewIqTip: "Atlas Pro Tip",
    recordReview: "Registra recensione",
    stopRecording: "Ferma registrazione",
    listeningNow: "In ascolto. Parla in modo naturale e la trascrizione apparirà qui sotto.",
    tapRecordAndSpeak: "Tocca registra e racconta la tua recensione a voce. Puoi anche modificare la trascrizione qui sotto.",
    voiceUnavailable: "L'input vocale non è disponibile in questo browser.",
    transcript: "Trascrizione",
    reviewTranscriptPlaceholder: "La tua recensione registrata apparirà qui mentre parli.",
    writePlaceholder: "Che cosa ti ha colpito di più del soggiorno? Inizia da dove vuoi.",
    excellentDetail: "Ottimo livello di dettaglio",
    gettingThere: "Ci sei quasi",
    keepGoing: "Continua così",
    keepTalking: "Continua a parlare",
    keepWriting: "Continua a scrivere",
    word: "parola",
    words: "parole",
    day: "giorno",
    days: "giorni",
    addPhotosOptional: "Aggiungi foto (facoltativo)",
    dragPhotos: "Trascina qui le foto o fai clic per caricarle",
    photoUploadSub: "JPG, PNG o HEIC.",
    uploadedPhotoAlt: "Foto caricata della struttura",
    nextPage: "Pagina successiva",
    submitReview: "Invia recensione",
    submitting: "Invio in corso...",
    adaptiveQuestions: "Domande adattive",
    adaptiveQuestionsCopy: "Rispondi agli ultimi 1 o 2 punti mancanti, oppure salta se non vuoi aggiungere altro.",
    skip: "Salta",
    findingBestFollowUp: "Cerco il miglior follow-up",
    followUpLoadingText: "Sto controllando dettagli mancanti, datati e in conflitto per capire cosa conta ancora di più.",
    noAdditionalQuestions: "Nessuna domanda aggiuntiva",
    noAdditionalQuestionsBody: "La tua recensione ha già coperto i punti più importanti per questa struttura.",
    noAdditionalQuestionsHelper: "Puoi inviare da qui senza rispondere ad altro.",
    questionOf: "Domanda {current} di {total} • {label}",
    recordAnswer: "Registra risposta",
    answerListeningNow: "In ascolto. Di' la tua risposta e la trascrizione apparirà qui sotto.",
    answerIdle: "Fai clic su Registra risposta quando sei pronto. Puoi modificare la trascrizione qui sotto se serve.",
    answerTranscriptPlaceholder: "La tua risposta registrata apparirà qui mentre parli.",
    addDetailIfSpecific: "Aggiungi qualche dettaglio se hai notato qualcosa di specifico.",
    answerCaptured: "Risposta acquisita. Puoi ancora modificarla prima di inviare.",
    travelerTasteProfile: "Profilo gusti del viaggiatore",
    tasteUpdated: "Aggiornato dopo questa recensione. Si ricalcola a ogni soggiorno.",
    matchedProperties: "Strutture adatte per il tuo prossimo viaggio",
    gapsClosed: "Gap chiusi",
    reviewsSubmitted: "Recensioni inviate",
    closedGaps: "Gap chiusi",
    freshTravelerEvidence: "Nuove evidenze del viaggiatore",
    refreshedFromReview: "{labels} aggiornato grazie a questa recensione.",
    whatYouShared: "Quello che hai condiviso",
    photos: "Foto",
    photosUploaded: "{count} foto caricate",
    reviewAnotherProperty: "Recensisci un'altra struttura",
    footerSubtitle: "Aiutiamo Expedia a raccogliere recensioni di viaggio più precise e più fresche.",
    footerNote: "Creato per le esperienze di feedback di viaggio Expedia.",
    puzzleTitle: "Rivela la struttura",
    didYouKnow: "Lo sapevi?",
    puzzleFallback: "Rispondi alle domande per rivelare i riquadri e sbloccare i dettagli della struttura.",
    doneModalAria: "Chiudi recensione inviata",
    reviewSubmitted: "Recensione inviata",
    reviewSubmittedBody: "La tua recensione è stata inviata. Continua ad Atlas Capsule per vedere arrivare il nuovo timbro.",
    continueToAtlasCapsule: "Continua ad Atlas Capsule",
    magicFixTyping: "Stiamo digitando ora le correzioni di grammatica, ortografia, punteggiatura e maiuscole. Potrai modificare la versione migliorata quando finisce.",
    magicFixReady: "Puoi guardare le correzioni comparire e poi accettarle o rifiutarle.",
    magicFixYourVersion: "La tua versione",
    magicFixEnhancedVersion: "Versione migliorata",
    magicFixSuggestedTitle: "Titolo suggerito",
    magicFixGeneratingTitle: "Generazione del titolo...",
    magicFixAddTitle: "Aggiungi un titolo",
    magicFixStatusLoading: "OpenAI sta migliorando la tua recensione e generando un titolo...",
    magicFixStatusApplying: "Applicazione delle correzioni...",
    magicFixStatusEditable: "Puoi modificare titolo e recensione prima di accettare.",
    magicFixTextareaPlaceholder: "Sto migliorando la tua recensione...",
    reviewSpeechIntro: "Raccontami del tuo soggiorno al {property}. Quando sei pronto, fai clic su Registra recensione per iniziare a parlare.",
    followUpSpeechIntro: "Follow-up intelligente. {prompt}.",
    nudgeStart: "Inizia da ciò che si è fatto notare di più: la camera, lo staff, la posizione o la sensazione generale.",
    nudgeThankYou: "Grazie per il tuo prezioso contributo.",
    yes: "Sì",
    no: "No",
    notSure: "Non sono sicuro",
    propertyFactAmenities: "I viaggiatori citano più spesso {items} qui.",
    propertyFactCheckIn: "L'annuncio attuale dice che il check-in è {value}.",
    propertyFactCheckOut: "Il check-out è indicato come {value}.",
    propertyFactLatestReview: "La recensione più recente nel dataset è stata registrata il {date}.",
    propertyFactRecentGuest: "Un ospite recente ha detto: {summary}",
    propertyFactRecentSlice: "{count} recensioni recenti aiutano a guidare la domanda di follow-up.",
    propertyFactTopGap: "Uno dei gap informativi di maggior valore riguarda {label}.",
    propertyFactAnotherGap: "Un altro tema probabilmente non aggiornato è {label}.",
    tasteInsight: "Le tue risposte hanno puntato soprattutto su {leader}, con {runnerUp} subito dietro. È proprio il tipo di segnale che una piattaforma di viaggi può usare per personalizzare le classifiche future e mettere in evidenza i dettagli che contano di più per te.",
    recommendationLeader: "Soggiorni orientati a {leader}",
    recommendationRunnerUp: "Scelte migliori per {runnerUp}",
    recommendationFresh: "Strutture aggiornate di recente",
    tasteValue: "Valore",
    tasteValueArchetype: "Ottimizzatore",
    tasteLocation: "Posizione",
    tasteLocationArchetype: "Esploratore",
    tasteComfort: "Comfort",
    tasteComfortArchetype: "Nidificante",
    tasteService: "Servizio",
    tasteServiceArchetype: "Fedele",
    tasteAmenities: "Servizi",
    tasteAmenitiesArchetype: "Coccolato",
    stampediaCapsule: "Capsule",
    travelCapsule: "Capsula di viaggio di {name}",
    travelCapsuleSub: "Soggiorni recensiti, conservati come ricordi",
    dateRange: "Intervallo date",
    duration: "Durata",
    country: "Paese",
    stamped: "Timbrato",
    stampediaPage: "Pagina {page}",
    closeReviewPreview: "Chiudi anteprima recensione",
    savedReview: "Recensione salvata",
    noStampsYetNote: "Ancora nessun timbro. Invia la prima recensione in {title} per iniziare questo diario.",
    newStampNote: "{property} è appena entrato nella tua pagina {title}.",
    stampsCollectedNote: "{count} raccolti per {country}.",
    openSavedReviewAria: "Apri recensione salvata per {property}",
    atlasCapsuleJournal: "Diario Atlas Capsule",
    noStampsYetCountry: "Ancora nessun timbro",
    firstReviewSubtitle: "Invia la tua prima recensione per iniziare a collezionare timbri.",
    countryJournal: "Diario {country}",
    recentStay: "Viaggio recente",
    qualityLabel: "{count} soggiorni recenti"
  },
  pt: {
    stepOf: "Etapa {current} de {total}",
    switchCustomer: "Trocar cliente",
    stepChooseStay: "Escolher estadia",
    stepInputStyle: "Modo de entrada",
    stepReview: "Avaliação",
    stepFollowUp: "Seguimento",
    stepProfile: "Perfil",
    chooseStayHeading: "Oi, {name}. Escolha uma das suas estadias recentes para avaliar.",
    checkIn: "Check-in",
    checkOut: "Check-out",
    roomType: "Tipo de quarto",
    confirmation: "Confirmação",
    allStaysReviewed: "Todas as estadias avaliadas",
    emptyQueue: "A fila de avaliações de {name} está vazia. O restante da jornada agora vive no Atlas Capsule.",
    goToAtlasCapsule: "Ir para Atlas Capsule",
    backToCustomers: "Voltar para clientes",
    shareHeading: "Como você gostaria de compartilhar, {name}?",
    writeYourReview: "Escrever sua avaliação",
    speakYourReview: "Falar sua avaliação",
    back: "Voltar",
    overallImpression: "Impressão geral",
    yourReview: "Sua avaliação",
    reviewIqTip: "Atlas Pro Tip",
    recordReview: "Gravar avaliação",
    stopRecording: "Parar gravação",
    listeningNow: "Ouvindo agora. Fale naturalmente e a transcrição aparecerá abaixo.",
    tapRecordAndSpeak: "Toque em gravar e fale sua avaliação em voz alta. Você também pode editar a transcrição abaixo.",
    voiceUnavailable: "A entrada por voz não está disponível neste navegador.",
    transcript: "Transcrição",
    reviewTranscriptPlaceholder: "Sua avaliação gravada aparecerá aqui enquanto você fala.",
    writePlaceholder: "O que mais se destacou na sua estadia? Comece por qualquer ponto.",
    excellentDetail: "Ótimo nível de detalhe",
    gettingThere: "Quase lá",
    keepGoing: "Continue",
    keepTalking: "Continue falando",
    keepWriting: "Continue escrevendo",
    word: "palavra",
    words: "palavras",
    day: "dia",
    days: "dias",
    addPhotosOptional: "Adicionar fotos (opcional)",
    dragPhotos: "Arraste fotos aqui ou clique para enviar",
    photoUploadSub: "JPG, PNG ou HEIC.",
    uploadedPhotoAlt: "Evidência enviada da propriedade",
    nextPage: "Próxima página",
    submitReview: "Enviar avaliação",
    submitting: "Enviando...",
    adaptiveQuestions: "Perguntas adaptativas",
    adaptiveQuestionsCopy: "Responda às últimas 1 ou 2 lacunas, ou pule se não quiser acrescentar mais nada.",
    skip: "Pular",
    findingBestFollowUp: "Buscando o melhor seguimento",
    followUpLoadingText: "Analisando detalhes ausentes, desatualizados e conflitantes para decidir o que ainda importa mais.",
    noAdditionalQuestions: "Sem perguntas adicionais",
    noAdditionalQuestionsBody: "Sua avaliação já cobriu as lacunas mais importantes desta propriedade.",
    noAdditionalQuestionsHelper: "Você pode enviar daqui sem responder mais nada.",
    questionOf: "Pergunta {current} de {total} • {label}",
    recordAnswer: "Gravar resposta",
    answerListeningNow: "Ouvindo agora. Fale sua resposta e a transcrição aparecerá abaixo.",
    answerIdle: "Clique em Gravar resposta quando estiver pronto. Você pode editar a transcrição abaixo se precisar.",
    answerTranscriptPlaceholder: "Sua resposta gravada aparecerá aqui enquanto você fala.",
    addDetailIfSpecific: "Adicione um pouco mais de detalhe se você notou algo específico.",
    answerCaptured: "Resposta registrada. Você ainda pode editá-la antes de enviar.",
    travelerTasteProfile: "Perfil de gosto do viajante",
    tasteUpdated: "Atualizado após esta avaliação. Recalculado a cada estadia.",
    matchedProperties: "Propriedades combinadas para sua próxima viagem",
    gapsClosed: "Lacunas fechadas",
    reviewsSubmitted: "Avaliações enviadas",
    closedGaps: "Lacunas fechadas",
    freshTravelerEvidence: "Novos sinais do viajante",
    refreshedFromReview: "{labels} foi atualizado com esta avaliação.",
    whatYouShared: "O que você compartilhou",
    photos: "Fotos",
    photosUploaded: "{count} fotos enviadas",
    reviewAnotherProperty: "Avaliar outra propriedade",
    footerSubtitle: "Ajudando a Expedia a coletar avaliações de viagem mais precisas e recentes.",
    footerNote: "Criado para experiências de feedback de viagem da Expedia.",
    puzzleTitle: "Revelar a propriedade",
    didYouKnow: "Você sabia?",
    puzzleFallback: "Responda às perguntas para revelar partes e desbloquear fatos da propriedade.",
    doneModalAria: "Fechar avaliação enviada",
    reviewSubmitted: "Avaliação enviada",
    reviewSubmittedBody: "Sua avaliação foi enviada. Continue para o Atlas Capsule para ver seu novo selo chegar.",
    continueToAtlasCapsule: "Continuar para Atlas Capsule",
    magicFixTyping: "Estamos digitando agora as correções de gramática, ortografia, pontuação e capitalização. Você poderá editar a versão aprimorada quando terminar.",
    magicFixReady: "Você pode ver as correções aparecerem e depois aceitá-las ou recusá-las.",
    magicFixYourVersion: "Sua versão",
    magicFixEnhancedVersion: "Versão aprimorada",
    magicFixSuggestedTitle: "Título sugerido",
    magicFixGeneratingTitle: "Gerando um título...",
    magicFixAddTitle: "Adicionar um título",
    magicFixStatusLoading: "A OpenAI está aprimorando sua avaliação e gerando um título...",
    magicFixStatusApplying: "Aplicando correções...",
    magicFixStatusEditable: "Você pode editar o título e a avaliação antes de aceitar.",
    magicFixTextareaPlaceholder: "Aprimorando sua avaliação...",
    reviewSpeechIntro: "Conte sobre sua estadia em {property}. Quando estiver pronto, clique em Gravar avaliação para começar a falar.",
    followUpSpeechIntro: "Seguimento inteligente. {prompt}.",
    nudgeStart: "Comece pelo que mais se destacou: o quarto, a equipe, a localização ou a impressão geral.",
    nudgeThankYou: "Obrigado pela sua contribuição valiosa.",
    yes: "Sim",
    no: "Não",
    notSure: "Não tenho certeza",
    propertyFactAmenities: "Os viajantes mencionam com mais frequência {items} aqui.",
    propertyFactCheckIn: "O anúncio atual informa que o check-in é {value}.",
    propertyFactCheckOut: "O check-out está listado como {value}.",
    propertyFactLatestReview: "A avaliação mais recente no conjunto de dados foi registrada em {date}.",
    propertyFactRecentGuest: "Um hóspede recente disse: {summary}",
    propertyFactRecentSlice: "{count} avaliações recentes ajudam a embasar a pergunta de seguimento.",
    propertyFactTopGap: "Uma das lacunas de informação mais valiosas é {label}.",
    propertyFactAnotherGap: "Outro tema provavelmente desatualizado é {label}.",
    tasteInsight: "Suas respostas penderam mais para {leader}, com {runnerUp} logo atrás. Esse é exatamente o tipo de sinal que uma plataforma de viagem pode usar para personalizar futuras classificações e destacar os fatos que mais importam para você.",
    recommendationLeader: "Estadias voltadas para {leader}",
    recommendationRunnerUp: "Melhores opções de {runnerUp}",
    recommendationFresh: "Listagens atualizadas recentemente",
    tasteValue: "Valor",
    tasteValueArchetype: "Otimizador",
    tasteLocation: "Localização",
    tasteLocationArchetype: "Explorador",
    tasteComfort: "Conforto",
    tasteComfortArchetype: "Aconchegado",
    tasteService: "Serviço",
    tasteServiceArchetype: "Fiel",
    tasteAmenities: "Comodidades",
    tasteAmenitiesArchetype: "Apreciador",
    stampediaCapsule: "Capsule",
    travelCapsule: "Cápsula de viagem de {name}",
    travelCapsuleSub: "Estadias avaliadas, guardadas como lembranças",
    dateRange: "Período",
    duration: "Duração",
    country: "País",
    stamped: "Carimbado",
    stampediaPage: "Página {page}",
    closeReviewPreview: "Fechar prévia da avaliação",
    savedReview: "Avaliação salva",
    noStampsYetNote: "Ainda não há selos. Envie a primeira avaliação em {title} para começar este diário.",
    newStampNote: "{property} acabou de entrar na sua página de {title}.",
    stampsCollectedNote: "{count} coletados para {country}.",
    openSavedReviewAria: "Abrir avaliação salva de {property}",
    atlasCapsuleJournal: "Diário Atlas Capsule",
    noStampsYetCountry: "Ainda sem selos",
    firstReviewSubtitle: "Envie sua primeira avaliação para começar a colecionar selos.",
    countryJournal: "Diário de {country}",
    recentStay: "Viagem recente",
    qualityLabel: "{count} estadias recentes"
  },
  ja: {
    stepOf: "{total}ステップ中{current}",
    switchCustomer: "顧客を切り替える",
    stepChooseStay: "滞在を選ぶ",
    stepInputStyle: "入力方法",
    stepReview: "レビュー",
    stepFollowUp: "追加質問",
    stepProfile: "プロフィール",
    chooseStayHeading: "こんにちは、{name}さん。最近の滞在からレビューするものを選んでください。",
    checkIn: "チェックイン",
    checkOut: "チェックアウト",
    roomType: "部屋タイプ",
    confirmation: "確認番号",
    allStaysReviewed: "すべての滞在をレビュー済みです",
    emptyQueue: "{name}さんのレビュー待ちはありません。残りの体験は Atlas Capsule に移りました。",
    goToAtlasCapsule: "Atlas Capsule へ",
    backToCustomers: "顧客一覧へ戻る",
    shareHeading: "{name}さん、どの方法で共有しますか？",
    writeYourReview: "レビューを書く",
    speakYourReview: "レビューを話す",
    back: "戻る",
    overallImpression: "全体の印象",
    yourReview: "あなたのレビュー",
    reviewIqTip: "Atlas Pro Tip",
    recordReview: "レビューを録音",
    stopRecording: "録音を停止",
    listeningNow: "聞き取り中です。自然に話すと下に文字起こしが表示されます。",
    tapRecordAndSpeak: "録音を押してレビューを声で話してください。下の文字起こしは編集できます。",
    voiceUnavailable: "このブラウザでは音声入力を利用できません。",
    transcript: "文字起こし",
    reviewTranscriptPlaceholder: "話している間、ここにレビューの文字起こしが表示されます。",
    writePlaceholder: "滞在で一番印象に残ったことは何ですか。どこからでも書き始めてください。",
    excellentDetail: "とても詳しいです",
    gettingThere: "もう少しです",
    keepGoing: "そのまま続けてください",
    keepTalking: "話し続けてください",
    keepWriting: "書き続けてください",
    word: "語",
    words: "語",
    day: "日",
    days: "日",
    addPhotosOptional: "写真を追加（任意）",
    dragPhotos: "ここに写真をドラッグするか、クリックしてアップロード",
    photoUploadSub: "JPG、PNG、または HEIC。",
    uploadedPhotoAlt: "アップロードされた施設写真",
    nextPage: "次のページ",
    submitReview: "レビューを送信",
    submitting: "送信中...",
    adaptiveQuestions: "追加質問",
    adaptiveQuestionsCopy: "残っている重要な1〜2件だけ答えるか、追加したくなければスキップできます。",
    skip: "スキップ",
    findingBestFollowUp: "最適な追加質問を選んでいます",
    followUpLoadingText: "不足・古い・矛盾する情報を見て、今まだ重要な点を判断しています。",
    noAdditionalQuestions: "追加質問はありません",
    noAdditionalQuestionsBody: "この施設について、あなたのレビューでもう重要な不足点はほぼ埋まりました。",
    noAdditionalQuestionsHelper: "これ以上答えなくてもここから送信できます。",
    questionOf: "質問 {current}/{total} • {label}",
    recordAnswer: "回答を録音",
    answerListeningNow: "聞き取り中です。回答を話すと下に文字起こしが表示されます。",
    answerIdle: "準備ができたら「回答を録音」を押してください。必要なら下で文字起こしを編集できます。",
    answerTranscriptPlaceholder: "話している間、ここに回答の文字起こしが表示されます。",
    addDetailIfSpecific: "何か具体的に気づいたことがあれば少し詳しく書いてください。",
    answerCaptured: "回答を保存しました。送信前にまだ編集できます。",
    travelerTasteProfile: "旅行者の好みプロフィール",
    tasteUpdated: "このレビュー後に更新されました。滞在ごとに再計算されます。",
    matchedProperties: "次の旅行に合う施設",
    gapsClosed: "埋まったギャップ",
    reviewsSubmitted: "送信したレビュー",
    closedGaps: "埋まったギャップ",
    freshTravelerEvidence: "新しい旅行者シグナル",
    refreshedFromReview: "{labels} がこのレビューで更新されました。",
    whatYouShared: "共有した内容",
    photos: "写真",
    photosUploaded: "{count}枚の写真をアップロードしました",
    reviewAnotherProperty: "別の施設をレビューする",
    footerSubtitle: "Expedia がより鋭く新鮮な旅行レビューを集められるよう支援します。",
    footerNote: "Expedia の旅行フィードバック体験のために作られています。",
    puzzleTitle: "施設を少しずつ表示",
    didYouKnow: "ご存じでしたか？",
    puzzleFallback: "質問に答えてピースを開き、施設情報を表示しましょう。",
    doneModalAria: "レビュー送信完了を閉じる",
    reviewSubmitted: "レビューを送信しました",
    reviewSubmittedBody: "レビューは送信されました。Atlas Capsule に進んで新しいスタンプを確認してください。",
    continueToAtlasCapsule: "Atlas Capsule に進む",
    magicFixTyping: "文法、スペル、句読点、大文字の修正を入力しています。終わったら改善版を編集できます。",
    magicFixReady: "修正が表示される様子を見てから、承認または拒否できます。",
    magicFixYourVersion: "元の内容",
    magicFixEnhancedVersion: "改善版",
    magicFixSuggestedTitle: "提案タイトル",
    magicFixGeneratingTitle: "タイトルを生成しています...",
    magicFixAddTitle: "タイトルを追加",
    magicFixStatusLoading: "OpenAI がレビューを整えてタイトルも生成しています...",
    magicFixStatusApplying: "修正を適用中...",
    magicFixStatusEditable: "承認する前にタイトルとレビューを編集できます。",
    magicFixTextareaPlaceholder: "レビューを整えています...",
    reviewSpeechIntro: "{property}での滞在について教えてください。準備ができたら「レビューを録音」を押して話し始めてください。",
    followUpSpeechIntro: "追加質問です。{prompt}。",
    nudgeStart: "部屋、スタッフ、立地、または全体の雰囲気など、最も印象に残ったことから始めてください。",
    nudgeThankYou: "貴重なご意見をありがとうございます。",
    yes: "はい",
    no: "いいえ",
    notSure: "わかりません",
    propertyFactAmenities: "この施設では {items} がよく話題になります。",
    propertyFactCheckIn: "現在の掲載情報ではチェックインは {value} です。",
    propertyFactCheckOut: "チェックアウトは {value} と表示されています。",
    propertyFactLatestReview: "データセット内の最新レビューは {date} に記録されています。",
    propertyFactRecentGuest: "最近の宿泊者の声: {summary}",
    propertyFactRecentSlice: "最近のレビュー {count} 件が追加質問の判断材料になっています。",
    propertyFactTopGap: "特に価値の高い情報ギャップの一つは {label} です。",
    propertyFactAnotherGap: "もう一つ古くなっている可能性が高い話題は {label} です。",
    tasteInsight: "あなたの回答は特に {leader} に寄っており、{runnerUp} がその次でした。これは、旅行プラットフォームが将来の順位付けを個別化し、あなたにとって重要な情報を強調するために使えるシグナルです。",
    recommendationLeader: "{leader} 重視の宿泊先",
    recommendationRunnerUp: "{runnerUp} が高評価の候補",
    recommendationFresh: "最近更新された掲載",
    tasteValue: "価値",
    tasteValueArchetype: "最適化派",
    tasteLocation: "立地",
    tasteLocationArchetype: "探索派",
    tasteComfort: "快適さ",
    tasteComfortArchetype: "くつろぎ派",
    tasteService: "サービス",
    tasteServiceArchetype: "ロイヤル派",
    tasteAmenities: "設備",
    tasteAmenitiesArchetype: "満喫派",
    stampediaCapsule: "Capsule",
    travelCapsule: "{name}さんのトラベルカプセル",
    travelCapsuleSub: "レビュー済みの滞在を思い出として保存",
    dateRange: "日程",
    duration: "期間",
    country: "国",
    stamped: "スタンプ済み",
    stampediaPage: "ページ {page}",
    closeReviewPreview: "保存したレビューを閉じる",
    savedReview: "保存したレビュー",
    noStampsYetNote: "まだスタンプはありません。{title} で最初のレビューを送信してこのジャーナルを始めましょう。",
    newStampNote: "{property} が {title} のページに追加されました。",
    stampsCollectedNote: "{country} で {count} 件集まりました。",
    openSavedReviewAria: "{property} の保存済みレビューを開く",
    atlasCapsuleJournal: "Atlas Capsule ジャーナル",
    noStampsYetCountry: "まだスタンプなし",
    firstReviewSubtitle: "最初のレビューを送信してスタンプ集めを始めましょう。",
    countryJournal: "{country} ジャーナル",
    recentStay: "最近の旅行",
    qualityLabel: "最近の滞在 {count} 件"
  },
  zh: {
    stepOf: "第 {current} 步，共 {total} 步",
    switchCustomer: "切换客户",
    stepChooseStay: "选择住宿",
    stepInputStyle: "输入方式",
    stepReview: "点评",
    stepFollowUp: "补充问题",
    stepProfile: "档案",
    chooseStayHeading: "你好，{name}。请选择一个最近的住宿来写点评。",
    checkIn: "入住",
    checkOut: "退房",
    roomType: "房型",
    confirmation: "确认号",
    allStaysReviewed: "所有住宿都已点评",
    emptyQueue: "{name} 的点评队列已空。接下来的旅程现在会保存在 Atlas Capsule 中。",
    goToAtlasCapsule: "前往 Atlas Capsule",
    backToCustomers: "返回客户列表",
    shareHeading: "{name}，你想怎么分享？",
    writeYourReview: "写点评",
    speakYourReview: "语音点评",
    back: "返回",
    overallImpression: "整体印象",
    yourReview: "你的点评",
    reviewIqTip: "Atlas Pro Tip",
    recordReview: "开始录音",
    stopRecording: "停止录音",
    listeningNow: "正在聆听。请自然说话，转写内容会显示在下方。",
    tapRecordAndSpeak: "点击录音并说出你的点评。你也可以在下方编辑转写内容。",
    voiceUnavailable: "此浏览器不支持语音输入。",
    transcript: "转写内容",
    reviewTranscriptPlaceholder: "你说话时，录制的点评会显示在这里。",
    writePlaceholder: "这次住宿中最让你印象深刻的是什么？从任何地方开始都可以。",
    excellentDetail: "内容很充分",
    gettingThere: "快好了",
    keepGoing: "继续",
    keepTalking: "继续说",
    keepWriting: "继续写",
    word: "词",
    words: "词",
    day: "天",
    days: "天",
    addPhotosOptional: "添加照片（可选）",
    dragPhotos: "把照片拖到这里，或点击上传",
    photoUploadSub: "支持 JPG、PNG 或 HEIC。",
    uploadedPhotoAlt: "已上传的酒店照片",
    nextPage: "下一页",
    submitReview: "提交点评",
    submitting: "提交中...",
    adaptiveQuestions: "补充问题",
    adaptiveQuestionsCopy: "再回答最后 1 到 2 个关键缺口；如果不想继续，也可以跳过。",
    skip: "跳过",
    findingBestFollowUp: "正在寻找最合适的补充问题",
    followUpLoadingText: "正在查看缺失、过时和相互冲突的信息，以判断哪些内容仍然最重要。",
    noAdditionalQuestions: "没有更多问题",
    noAdditionalQuestionsBody: "你的点评已经补足了这家酒店最有价值的信息缺口。",
    noAdditionalQuestionsHelper: "你可以直接从这里提交，无需再回答其他问题。",
    questionOf: "问题 {current}/{total} • {label}",
    recordAnswer: "录制回答",
    answerListeningNow: "正在聆听。请说出你的回答，转写内容会显示在下方。",
    answerIdle: "准备好后点击“录制回答”。如有需要，你也可以在下方编辑转写内容。",
    answerTranscriptPlaceholder: "你说话时，录制的回答会显示在这里。",
    addDetailIfSpecific: "如果你注意到了更具体的细节，可以再补充一点。",
    answerCaptured: "回答已记录。提交前你仍可继续编辑。",
    travelerTasteProfile: "旅行偏好画像",
    tasteUpdated: "本次点评后已更新。每次住宿都会重新计算。",
    matchedProperties: "适合你下一次旅行的酒店",
    gapsClosed: "已补足缺口",
    reviewsSubmitted: "已提交点评",
    closedGaps: "已补足缺口",
    freshTravelerEvidence: "新的旅客信号",
    refreshedFromReview: "{labels} 已通过这条点评得到更新。",
    whatYouShared: "你分享的内容",
    photos: "照片",
    photosUploaded: "已上传 {count} 张照片",
    reviewAnotherProperty: "点评另一家酒店",
    footerSubtitle: "帮助 Expedia 收集更清晰、更新鲜的旅行点评。",
    footerNote: "为 Expedia 旅行反馈体验而构建。",
    puzzleTitle: "逐步揭开酒店",
    didYouKnow: "你知道吗？",
    puzzleFallback: "回答问题即可解锁拼图，并显示更多酒店信息。",
    doneModalAria: "关闭点评已提交弹窗",
    reviewSubmitted: "点评已提交",
    reviewSubmittedBody: "你的点评已提交。继续前往 Atlas Capsule 查看新印章。",
    continueToAtlasCapsule: "继续前往 Atlas Capsule",
    magicFixTyping: "我们正在输入语法、拼写、标点和大小写修正。完成后你可以编辑增强后的版本。",
    magicFixReady: "你可以看到修改逐步出现，然后选择接受或拒绝。",
    magicFixYourVersion: "你的原文",
    magicFixEnhancedVersion: "增强版本",
    magicFixSuggestedTitle: "推荐标题",
    magicFixGeneratingTitle: "正在生成标题...",
    magicFixAddTitle: "添加标题",
    magicFixStatusLoading: "OpenAI 正在润色你的点评并生成标题...",
    magicFixStatusApplying: "正在应用修改...",
    magicFixStatusEditable: "接受前，你可以编辑标题和点评。",
    magicFixTextareaPlaceholder: "正在润色你的点评...",
    reviewSpeechIntro: "请告诉我你在 {property} 的住宿体验。准备好后，请点击“开始录音”开始说话。",
    followUpSpeechIntro: "智能补充问题。{prompt}。",
    nudgeStart: "先从最突出的部分说起：房间、员工、位置，或整体感受。",
    nudgeThankYou: "感谢你的宝贵反馈。",
    yes: "是",
    no: "否",
    notSure: "不确定",
    propertyFactAmenities: "旅客在这里最常提到的是 {items}。",
    propertyFactCheckIn: "当前房源信息显示，入住时间为 {value}。",
    propertyFactCheckOut: "退房时间显示为 {value}。",
    propertyFactLatestReview: "数据集中最近的一条点评记录于 {date}。",
    propertyFactRecentGuest: "最近一位住客说：{summary}",
    propertyFactRecentSlice: "最近这段时间的 {count} 条点评帮助确定补充问题。",
    propertyFactTopGap: "最值得补充的信息缺口之一是 {label}。",
    propertyFactAnotherGap: "另一个可能已经过时的话题是 {label}。",
    tasteInsight: "你的回答最偏向 {leader}，其次是 {runnerUp}。这种画像正是旅行平台可以用来个性化未来排序、突出你最在意信息的信号。",
    recommendationLeader: "偏重 {leader} 的住宿",
    recommendationRunnerUp: "{runnerUp} 评分更高的选择",
    recommendationFresh: "最近更新的房源",
    tasteValue: "性价比",
    tasteValueArchetype: "优化型",
    tasteLocation: "位置",
    tasteLocationArchetype: "探索型",
    tasteComfort: "舒适度",
    tasteComfortArchetype: "安逸型",
    tasteService: "服务",
    tasteServiceArchetype: "忠诚型",
    tasteAmenities: "设施",
    tasteAmenitiesArchetype: "享受型",
    stampediaCapsule: "Capsule",
    travelCapsule: "{name} 的旅行胶囊",
    travelCapsuleSub: "已点评的住宿，作为纪念保存",
    dateRange: "日期范围",
    duration: "时长",
    country: "国家",
    stamped: "已盖章",
    stampediaPage: "第 {page} 页",
    closeReviewPreview: "关闭已保存点评预览",
    savedReview: "已保存点评",
    noStampsYetNote: "还没有印章。提交 {title} 中的第一条点评即可开始这本旅行册。",
    newStampNote: "{property} 刚刚进入你的 {title} 页面。",
    stampsCollectedNote: "{country} 已收集 {count} 枚。",
    openSavedReviewAria: "打开 {property} 的已保存点评",
    atlasCapsuleJournal: "Atlas Capsule 日志",
    noStampsYetCountry: "还没有印章",
    firstReviewSubtitle: "提交第一条点评即可开始收集印章。",
    countryJournal: "{country} 旅行册",
    recentStay: "最近一次旅行",
    qualityLabel: "最近 {count} 次住宿"
  },
  ar: {
    stepOf: "الخطوة {current} من {total}",
    switchCustomer: "تبديل العميل",
    stepChooseStay: "اختيار الإقامة",
    stepInputStyle: "طريقة الإدخال",
    stepReview: "المراجعة",
    stepFollowUp: "أسئلة متابعة",
    stepProfile: "الملف",
    chooseStayHeading: "مرحبًا {name}، اختر واحدة من إقاماتك الأخيرة لمراجعتها.",
    checkIn: "تسجيل الوصول",
    checkOut: "تسجيل المغادرة",
    roomType: "نوع الغرفة",
    confirmation: "رقم التأكيد",
    allStaysReviewed: "تمت مراجعة جميع الإقامات",
    emptyQueue: "قائمة مراجعات {name} فارغة الآن. بقية الرحلة أصبحت داخل Atlas Capsule.",
    goToAtlasCapsule: "الانتقال إلى Atlas Capsule",
    backToCustomers: "العودة إلى العملاء",
    shareHeading: "كيف تود أن تشارك يا {name}؟",
    writeYourReview: "اكتب مراجعتك",
    speakYourReview: "تحدث بمراجعتك",
    back: "رجوع",
    overallImpression: "الانطباع العام",
    yourReview: "مراجعتك",
    reviewIqTip: "Atlas Pro Tip",
    recordReview: "تسجيل المراجعة",
    stopRecording: "إيقاف التسجيل",
    listeningNow: "نستمع الآن. تحدث بشكل طبيعي وسيظهر النص في الأسفل.",
    tapRecordAndSpeak: "اضغط على التسجيل وتحدث بصوتك. ويمكنك أيضًا تعديل النص في الأسفل.",
    voiceUnavailable: "الإدخال الصوتي غير متاح في هذا المتصفح.",
    transcript: "النص",
    reviewTranscriptPlaceholder: "ستظهر مراجعتك المسجلة هنا أثناء حديثك.",
    writePlaceholder: "ما أكثر شيء لفت انتباهك في الإقامة؟ ابدأ من أي نقطة.",
    excellentDetail: "تفاصيل ممتازة",
    gettingThere: "أنت تقترب",
    keepGoing: "استمر",
    keepTalking: "استمر في التحدث",
    keepWriting: "استمر في الكتابة",
    word: "كلمة",
    words: "كلمات",
    day: "يوم",
    days: "أيام",
    addPhotosOptional: "إضافة صور (اختياري)",
    dragPhotos: "اسحب الصور هنا أو انقر للرفع",
    photoUploadSub: "JPG أو PNG أو HEIC.",
    uploadedPhotoAlt: "صورة مرفوعة للفندق",
    nextPage: "الصفحة التالية",
    submitReview: "إرسال المراجعة",
    submitting: "جارٍ الإرسال...",
    adaptiveQuestions: "أسئلة متابعة",
    adaptiveQuestionsCopy: "أجب عن آخر نقطة أو نقطتين مهمتين، أو تخطَّ ذلك إذا لم ترغب في إضافة المزيد.",
    skip: "تخطي",
    findingBestFollowUp: "نبحث عن أفضل سؤال متابعة",
    followUpLoadingText: "نراجع التفاصيل الناقصة أو القديمة أو المتعارضة لمعرفة ما يزال مهمًا أكثر.",
    noAdditionalQuestions: "لا توجد أسئلة إضافية",
    noAdditionalQuestionsBody: "مراجعتك غطّت بالفعل أهم الفجوات لهذه المنشأة.",
    noAdditionalQuestionsHelper: "يمكنك الإرسال من هنا من دون الإجابة عن أي شيء آخر.",
    questionOf: "السؤال {current} من {total} • {label}",
    recordAnswer: "تسجيل الإجابة",
    answerListeningNow: "نستمع الآن. تحدث بإجابتك وسيظهر النص في الأسفل.",
    answerIdle: "اضغط على تسجيل الإجابة عندما تكون جاهزًا. ويمكنك تعديل النص في الأسفل إذا لزم الأمر.",
    answerTranscriptPlaceholder: "ستظهر إجابتك المسجلة هنا أثناء حديثك.",
    addDetailIfSpecific: "أضف بعض التفاصيل إن لاحظت شيئًا محددًا.",
    answerCaptured: "تم حفظ الإجابة. ما زال بإمكانك تعديلها قبل الإرسال.",
    travelerTasteProfile: "ملف ذوق المسافر",
    tasteUpdated: "تم تحديثه بعد هذه المراجعة. ويُعاد حسابه مع كل إقامة.",
    matchedProperties: "أماكن مناسبة لرحلتك القادمة",
    gapsClosed: "فجوات أُغلقت",
    reviewsSubmitted: "مراجعات أُرسلت",
    closedGaps: "الفجوات المغلقة",
    freshTravelerEvidence: "إشارات جديدة من المسافر",
    refreshedFromReview: "تم تحديث {labels} من هذه المراجعة.",
    whatYouShared: "ما شاركته",
    photos: "الصور",
    photosUploaded: "تم رفع {count} صورة",
    reviewAnotherProperty: "مراجعة منشأة أخرى",
    footerSubtitle: "نساعد Expedia على جمع مراجعات سفر أوضح وأكثر حداثة.",
    footerNote: "مبني لتجارب ملاحظات السفر لدى Expedia.",
    puzzleTitle: "اكشف المنشأة",
    didYouKnow: "هل تعلم؟",
    puzzleFallback: "أجب عن الأسئلة لكشف الأجزاء وفتح معلومات المنشأة.",
    doneModalAria: "إغلاق رسالة إرسال المراجعة",
    reviewSubmitted: "تم إرسال المراجعة",
    reviewSubmittedBody: "تم إرسال مراجعتك. تابع إلى Atlas Capsule لرؤية الختم الجديد.",
    continueToAtlasCapsule: "المتابعة إلى Atlas Capsule",
    magicFixTyping: "نكتب الآن تصحيحات القواعد والإملاء وعلامات الترقيم والحروف الكبيرة. ويمكنك تعديل النسخة المحسنة بعد الانتهاء.",
    magicFixReady: "يمكنك مشاهدة التصحيحات وهي تظهر ثم قبولها أو رفضها.",
    magicFixYourVersion: "نسختك",
    magicFixEnhancedVersion: "النسخة المحسنة",
    magicFixSuggestedTitle: "عنوان مقترح",
    magicFixGeneratingTitle: "جارٍ إنشاء عنوان...",
    magicFixAddTitle: "إضافة عنوان",
    magicFixStatusLoading: "تعمل OpenAI على تحسين مراجعتك وإنشاء عنوان...",
    magicFixStatusApplying: "جارٍ تطبيق التصحيحات...",
    magicFixStatusEditable: "يمكنك تعديل العنوان والمراجعة قبل القبول.",
    magicFixTextareaPlaceholder: "جارٍ تحسين مراجعتك...",
    reviewSpeechIntro: "حدثني عن إقامتك في {property}. عندما تكون جاهزًا، اضغط على تسجيل المراجعة للبدء في التحدث.",
    followUpSpeechIntro: "متابعة ذكية. {prompt}.",
    nudgeStart: "ابدأ بما لفت انتباهك أكثر: الغرفة، أو الموظفون، أو الموقع، أو الانطباع العام.",
    nudgeThankYou: "شكرًا على مدخلاتك القيّمة.",
    yes: "نعم",
    no: "لا",
    notSure: "لست متأكدًا",
    propertyFactAmenities: "غالبًا ما يذكر المسافرون هنا {items}.",
    propertyFactCheckIn: "تشير القائمة الحالية إلى أن تسجيل الوصول هو {value}.",
    propertyFactCheckOut: "وقت المغادرة المدرج هو {value}.",
    propertyFactLatestReview: "أحدث مراجعة في مجموعة البيانات سُجلت في {date}.",
    propertyFactRecentGuest: "قال أحد الضيوف مؤخرًا: {summary}",
    propertyFactRecentSlice: "يساعد {count} من المراجعات الحديثة في تحديد سؤال المتابعة.",
    propertyFactTopGap: "إحدى أهم فجوات المعلومات هي {label}.",
    propertyFactAnotherGap: "موضوع آخر يُحتمل أن يكون قديمًا هو {label}.",
    tasteInsight: "مالت إجاباتك أكثر نحو {leader}، مع اقتراب {runnerUp} منها. وهذا بالضبط النوع من الإشارات الذي يمكن لمنصة سفر أن تستخدمه لتخصيص التصنيفات المستقبلية وإبراز المعلومات التي تهمك أكثر.",
    recommendationLeader: "إقامات تركّز على {leader}",
    recommendationRunnerUp: "أفضل الخيارات في {runnerUp}",
    recommendationFresh: "إعلانات تم تحديثها مؤخرًا",
    tasteValue: "القيمة",
    tasteValueArchetype: "محسّن",
    tasteLocation: "الموقع",
    tasteLocationArchetype: "مستكشف",
    tasteComfort: "الراحة",
    tasteComfortArchetype: "محب للهدوء",
    tasteService: "الخدمة",
    tasteServiceArchetype: "وفيّ",
    tasteAmenities: "المرافق",
    tasteAmenitiesArchetype: "مستمتع",
    stampediaCapsule: "Capsule",
    travelCapsule: "كبسولة سفر {name}",
    travelCapsuleSub: "إقامات تمت مراجعتها وحفظها كتذكارات",
    dateRange: "الفترة",
    duration: "المدة",
    country: "البلد",
    stamped: "مختوم",
    stampediaPage: "الصفحة {page}",
    closeReviewPreview: "إغلاق معاينة المراجعة",
    savedReview: "مراجعة محفوظة",
    noStampsYetNote: "لا توجد أختام بعد. أرسل أول مراجعة في {title} لبدء هذا الدفتر.",
    newStampNote: "انضمت {property} للتو إلى صفحة {title}.",
    stampsCollectedNote: "تم جمع {count} لـ {country}.",
    openSavedReviewAria: "فتح المراجعة المحفوظة لـ {property}",
    atlasCapsuleJournal: "دفتر Atlas Capsule",
    noStampsYetCountry: "لا أختام بعد",
    firstReviewSubtitle: "أرسل أول مراجعة لتبدأ جمع الأختام.",
    countryJournal: "دفتر {country}",
    recentStay: "رحلة حديثة",
    qualityLabel: "{count} إقامات حديثة"
  },
  hi: {
    stepOf: "कदम {current} / {total}",
    switchCustomer: "ग्राहक बदलें",
    stepChooseStay: "स्टे चुनें",
    stepInputStyle: "इनपुट तरीका",
    stepReview: "रिव्यू",
    stepFollowUp: "फॉलो-अप",
    stepProfile: "प्रोफ़ाइल",
    chooseStayHeading: "हाय {name}, रिव्यू करने के लिए अपनी हाल की किसी स्टे को चुनें।",
    checkIn: "चेक-इन",
    checkOut: "चेक-आउट",
    roomType: "रूम टाइप",
    confirmation: "कन्फर्मेशन",
    allStaysReviewed: "सभी स्टे रिव्यू हो चुके हैं",
    emptyQueue: "{name} की रिव्यू कतार खाली है। बाकी यात्रा अब Atlas Capsule में है।",
    goToAtlasCapsule: "Atlas Capsule पर जाएँ",
    backToCustomers: "ग्राहकों पर वापस जाएँ",
    shareHeading: "{name}, आप कैसे साझा करना चाहेंगे?",
    writeYourReview: "अपना रिव्यू लिखें",
    speakYourReview: "अपना रिव्यू बोलें",
    back: "वापस",
    overallImpression: "कुल अनुभव",
    yourReview: "आपका रिव्यू",
    reviewIqTip: "Atlas Pro Tip",
    recordReview: "रिव्यू रिकॉर्ड करें",
    stopRecording: "रिकॉर्डिंग रोकें",
    listeningNow: "अभी सुन रहा है। सामान्य रूप से बोलें, ट्रांसक्रिप्ट नीचे दिखेगा।",
    tapRecordAndSpeak: "रिकॉर्ड दबाएँ और अपना रिव्यू बोलें। आप नीचे ट्रांसक्रिप्ट को एडिट भी कर सकते हैं।",
    voiceUnavailable: "इस ब्राउज़र में वॉइस इनपुट उपलब्ध नहीं है।",
    transcript: "ट्रांसक्रिप्ट",
    reviewTranscriptPlaceholder: "आपके बोलते समय रिकॉर्ड किया गया रिव्यू यहाँ दिखाई देगा।",
    writePlaceholder: "आपके स्टे में सबसे ज़्यादा क्या अलग लगा? कहीं से भी शुरू करें।",
    excellentDetail: "बहुत अच्छा विवरण",
    gettingThere: "अच्छा चल रहा है",
    keepGoing: "जारी रखें",
    keepTalking: "बोलते रहें",
    keepWriting: "लिखते रहें",
    word: "शब्द",
    words: "शब्द",
    day: "दिन",
    days: "दिन",
    addPhotosOptional: "फ़ोटो जोड़ें (वैकल्पिक)",
    dragPhotos: "फ़ोटो यहाँ खींचें या अपलोड करने के लिए क्लिक करें",
    photoUploadSub: "JPG, PNG या HEIC.",
    uploadedPhotoAlt: "अपलोड की गई प्रॉपर्टी फ़ोटो",
    nextPage: "अगला पेज",
    submitReview: "रिव्यू सबमिट करें",
    submitting: "सबमिट हो रहा है...",
    adaptiveQuestions: "फॉलो-अप सवाल",
    adaptiveQuestionsCopy: "आखिरी 1-2 ज़रूरी बातों का जवाब दें, या चाहें तो इसे छोड़ दें।",
    skip: "छोड़ें",
    findingBestFollowUp: "सबसे अच्छा फॉलो-अप ढूँढा जा रहा है",
    followUpLoadingText: "कमी, पुरानी और विरोधाभासी जानकारी देखकर तय किया जा रहा है कि अब भी क्या सबसे ज़रूरी है।",
    noAdditionalQuestions: "कोई अतिरिक्त सवाल नहीं",
    noAdditionalQuestionsBody: "आपके रिव्यू ने इस प्रॉपर्टी की सबसे अहम जानकारी की कमी पहले ही भर दी है।",
    noAdditionalQuestionsHelper: "आप यहाँ से बिना कुछ और जवाब दिए सबमिट कर सकते हैं।",
    questionOf: "सवाल {current} / {total} • {label}",
    recordAnswer: "जवाब रिकॉर्ड करें",
    answerListeningNow: "अभी सुन रहा है। अपना जवाब बोलें, ट्रांसक्रिप्ट नीचे दिखेगा।",
    answerIdle: "जब तैयार हों तो जवाब रिकॉर्ड करें पर क्लिक करें। ज़रूरत हो तो नीचे ट्रांसक्रिप्ट को एडिट कर सकते हैं।",
    answerTranscriptPlaceholder: "आपके बोलते समय रिकॉर्ड किया गया जवाब यहाँ दिखाई देगा।",
    addDetailIfSpecific: "अगर आपने कुछ खास नोटिस किया हो तो थोड़ा और विवरण जोड़ें।",
    answerCaptured: "जवाब सेव हो गया। सबमिट करने से पहले आप इसे अभी भी एडिट कर सकते हैं।",
    travelerTasteProfile: "यात्री पसंद प्रोफ़ाइल",
    tasteUpdated: "इस रिव्यू के बाद अपडेट किया गया। हर स्टे के साथ दोबारा कैलकुलेट होता है।",
    matchedProperties: "आपकी अगली यात्रा के लिए मेल खाने वाली प्रॉपर्टियाँ",
    gapsClosed: "भरे गए गैप",
    reviewsSubmitted: "सबमिट किए गए रिव्यू",
    closedGaps: "भरे गए गैप",
    freshTravelerEvidence: "नई यात्री जानकारी",
    refreshedFromReview: "{labels} इस रिव्यू से अपडेट हुआ।",
    whatYouShared: "आपने क्या साझा किया",
    photos: "फ़ोटो",
    photosUploaded: "{count} फ़ोटो अपलोड की गईं",
    reviewAnotherProperty: "किसी और प्रॉपर्टी का रिव्यू करें",
    footerSubtitle: "Expedia को और बेहतर और ताज़ा यात्रा रिव्यू इकट्ठा करने में मदद करना।",
    footerNote: "Expedia के ट्रैवल फ़ीडबैक अनुभवों के लिए बनाया गया।",
    puzzleTitle: "प्रॉपर्टी दिखाएँ",
    didYouKnow: "क्या आप जानते हैं?",
    puzzleFallback: "टुकड़े खोलने और प्रॉपर्टी की जानकारी देखने के लिए सवालों के जवाब दें।",
    doneModalAria: "रिव्यू सबमिट हुआ संदेश बंद करें",
    reviewSubmitted: "रिव्यू सबमिट हो गया",
    reviewSubmittedBody: "आपका रिव्यू सबमिट हो गया है। अपना नया स्टैम्प देखने के लिए Atlas Capsule पर जाएँ।",
    continueToAtlasCapsule: "Atlas Capsule पर जाएँ",
    magicFixTyping: "हम अभी व्याकरण, वर्तनी, विराम चिह्न और कैपिटलाइज़ेशन की सुधार टाइप कर रहे हैं। पूरा होने पर आप बेहतर किया गया संस्करण एडिट कर सकते हैं।",
    magicFixReady: "आप बदलावों को आते हुए देख सकते हैं, फिर उन्हें स्वीकार या अस्वीकार कर सकते हैं।",
    magicFixYourVersion: "आपका संस्करण",
    magicFixEnhancedVersion: "बेहतर किया गया संस्करण",
    magicFixSuggestedTitle: "सुझाया गया शीर्षक",
    magicFixGeneratingTitle: "शीर्षक बनाया जा रहा है...",
    magicFixAddTitle: "शीर्षक जोड़ें",
    magicFixStatusLoading: "OpenAI आपके रिव्यू को सुधार रहा है और शीर्षक बना रहा है...",
    magicFixStatusApplying: "सुधार लागू किए जा रहे हैं...",
    magicFixStatusEditable: "स्वीकार करने से पहले आप शीर्षक और रिव्यू एडिट कर सकते हैं।",
    magicFixTextareaPlaceholder: "आपका रिव्यू सुधारा जा रहा है...",
    reviewSpeechIntro: "{property} में आपके स्टे के बारे में बताइए। जब आप तैयार हों, तो बोलना शुरू करने के लिए रिव्यू रिकॉर्ड करें पर क्लिक करें।",
    followUpSpeechIntro: "स्मार्ट फॉलो-अप। {prompt}।",
    nudgeStart: "जो सबसे ज़्यादा अलग लगा उससे शुरू करें: कमरा, स्टाफ, लोकेशन या पूरा अनुभव।",
    nudgeThankYou: "आपकी मूल्यवान राय के लिए धन्यवाद।",
    yes: "हाँ",
    no: "नहीं",
    notSure: "पक्का नहीं",
    propertyFactAmenities: "यात्री यहाँ अक्सर {items} का ज़िक्र करते हैं।",
    propertyFactCheckIn: "मौजूदा लिस्टिंग के अनुसार चेक-इन {value} है।",
    propertyFactCheckOut: "चेक-आउट {value} बताया गया है।",
    propertyFactLatestReview: "डेटासेट में सबसे हाल का रिव्यू {date} को दर्ज किया गया था।",
    propertyFactRecentGuest: "एक हाल के मेहमान ने कहा: {summary}",
    propertyFactRecentSlice: "हाल की {count} समीक्षाएँ फॉलो-अप सवाल तय करने में मदद करती हैं।",
    propertyFactTopGap: "सबसे अहम जानकारी की कमियों में से एक है {label}।",
    propertyFactAnotherGap: "एक और विषय जो पुराना हो सकता है, वह है {label}।",
    tasteInsight: "आपके जवाब सबसे ज़्यादा {leader} की ओर झुके, और उसके बाद {runnerUp} रहा। यही वह संकेत है जिसका उपयोग कोई ट्रैवल प्लेटफ़ॉर्म भविष्य की रैंकिंग को निजी बनाने और आपके लिए महत्वपूर्ण बातों को सामने लाने में कर सकता है।",
    recommendationLeader: "{leader} केंद्रित ठहराव",
    recommendationRunnerUp: "{runnerUp} के बेहतरीन विकल्प",
    recommendationFresh: "हाल ही में अपडेट की गई लिस्टिंग",
    tasteValue: "मूल्य",
    tasteValueArchetype: "ऑप्टिमाइज़र",
    tasteLocation: "लोकेशन",
    tasteLocationArchetype: "एक्सप्लोरर",
    tasteComfort: "आराम",
    tasteComfortArchetype: "नेस्टर",
    tasteService: "सेवा",
    tasteServiceArchetype: "वफ़ादार",
    tasteAmenities: "सुविधाएँ",
    tasteAmenitiesArchetype: "आनंद लेने वाला",
    stampediaCapsule: "Capsule",
    travelCapsule: "{name} का ट्रैवल कैप्सूल",
    travelCapsuleSub: "रिव्यू की गई स्टे, यादों की तरह सहेजी गई",
    dateRange: "तारीख़ें",
    duration: "अवधि",
    country: "देश",
    stamped: "स्टैम्प किया गया",
    stampediaPage: "पेज {page}",
    closeReviewPreview: "सेव किया गया रिव्यू बंद करें",
    savedReview: "सेव किया गया रिव्यू",
    noStampsYetNote: "अभी कोई स्टैम्प नहीं है। इस जर्नल को शुरू करने के लिए {title} में पहला रिव्यू भेजें।",
    newStampNote: "{property} अभी आपके {title} पेज में जुड़ा है।",
    stampsCollectedNote: "{country} के लिए {count} एकत्र हुए।",
    openSavedReviewAria: "{property} का सेव किया गया रिव्यू खोलें",
    atlasCapsuleJournal: "Atlas Capsule जर्नल",
    noStampsYetCountry: "अभी कोई स्टैम्प नहीं",
    firstReviewSubtitle: "स्टैम्प इकट्ठा करना शुरू करने के लिए अपना पहला रिव्यू भेजें।",
    countryJournal: "{country} जर्नल",
    recentStay: "हाल की यात्रा",
    qualityLabel: "{count} हाल की स्टे"
  },
  nl: {
    stepOf: "Stap {current} van {total}",
    switchCustomer: "Klant wisselen",
    stepChooseStay: "Verblijf kiezen",
    stepInputStyle: "Invoerstijl",
    stepReview: "Review",
    stepFollowUp: "Vervolg",
    stepProfile: "Profiel",
    chooseStayHeading: "Hoi {name}, kies een van je recente verblijven om te beoordelen.",
    checkIn: "Inchecken",
    checkOut: "Uitchecken",
    roomType: "Kamertype",
    confirmation: "Bevestiging",
    allStaysReviewed: "Alle verblijven beoordeeld",
    emptyQueue: "De reviewwachtrij van {name} is leeg. De rest van de reis leeft nu in Atlas Capsule.",
    goToAtlasCapsule: "Ga naar Atlas Capsule",
    backToCustomers: "Terug naar klanten",
    shareHeading: "Hoe wil je delen, {name}?",
    writeYourReview: "Schrijf je review",
    speakYourReview: "Spreek je review in",
    back: "Terug",
    overallImpression: "Algemene indruk",
    yourReview: "Jouw review",
    reviewIqTip: "ReviewIQ",
    recordReview: "Review opnemen",
    stopRecording: "Opname stoppen",
    listeningNow: "Luistert nu. Spreek natuurlijk en het transcript verschijnt hieronder.",
    tapRecordAndSpeak: "Tik op opnemen en vertel je review hardop. Je kunt het transcript hieronder ook bewerken.",
    voiceUnavailable: "Spraakinvoer is niet beschikbaar in deze browser.",
    transcript: "Transcript",
    reviewTranscriptPlaceholder: "Je opgenomen review verschijnt hier terwijl je spreekt.",
    writePlaceholder: "Wat viel het meest op aan je verblijf? Begin waar je wilt.",
    excellentDetail: "Sterk detailniveau",
    gettingThere: "Je komt er",
    keepGoing: "Ga door",
    keepTalking: "Blijf praten",
    keepWriting: "Blijf schrijven",
    word: "woord",
    words: "woorden",
    day: "dag",
    days: "dagen",
    addPhotosOptional: "Foto's toevoegen (optioneel)",
    dragPhotos: "Sleep foto's hierheen of klik om te uploaden",
    photoUploadSub: "JPG, PNG of HEIC.",
    uploadedPhotoAlt: "Geüploade foto van de accommodatie",
    nextPage: "Volgende pagina",
    submitReview: "Review versturen",
    submitting: "Bezig met versturen...",
    adaptiveQuestions: "Adaptieve vragen",
    adaptiveQuestionsCopy: "Beantwoord de laatste 1-2 open punten, of sla ze over als je niets meer wilt toevoegen.",
    skip: "Overslaan",
    findingBestFollowUp: "Beste vervolgvraag wordt gezocht",
    followUpLoadingText: "Ontbrekende, verouderde en tegenstrijdige details worden bekeken om te bepalen wat nog het belangrijkst is.",
    noAdditionalQuestions: "Geen extra vragen",
    noAdditionalQuestionsBody: "Je review heeft de belangrijkste open punten voor deze accommodatie al afgedekt.",
    noAdditionalQuestionsHelper: "Je kunt vanaf hier indienen zonder nog iets te beantwoorden.",
    questionOf: "Vraag {current} van {total} • {label}",
    recordAnswer: "Antwoord opnemen",
    answerListeningNow: "Luistert nu. Spreek je antwoord en het transcript verschijnt hieronder.",
    answerIdle: "Klik op Antwoord opnemen wanneer je klaar bent. Je kunt het transcript hieronder nog aanpassen.",
    answerTranscriptPlaceholder: "Je opgenomen antwoord verschijnt hier terwijl je spreekt.",
    addDetailIfSpecific: "Voeg nog wat detail toe als je iets specifieks hebt gemerkt.",
    answerCaptured: "Antwoord vastgelegd. Je kunt het nog aanpassen voordat je verstuurt.",
    travelerTasteProfile: "Reissmaakprofiel",
    tasteUpdated: "Bijgewerkt na deze review. Wordt opnieuw berekend na elk verblijf.",
    matchedProperties: "Passende accommodaties voor je volgende reis",
    gapsClosed: "Dichtgemaakte gaten",
    reviewsSubmitted: "Verstuurde reviews",
    closedGaps: "Gesloten gaten",
    freshTravelerEvidence: "Nieuwe reizigerssignalen",
    refreshedFromReview: "{labels} is vernieuwd door deze review.",
    whatYouShared: "Wat je hebt gedeeld",
    photos: "Foto's",
    photosUploaded: "{count} foto's geüpload",
    reviewAnotherProperty: "Nog een accommodatie reviewen",
    footerSubtitle: "Expedia helpen om scherpere en actuelere reisreviews te verzamelen.",
    footerNote: "Gebouwd voor Expedia-ervaringen rond reisfeedback.",
    puzzleTitle: "Onthul de accommodatie",
    didYouKnow: "Wist je dit?",
    puzzleFallback: "Beantwoord vragen om vakken te onthullen en accommodatiefeiten vrij te spelen.",
    doneModalAria: "Verstuurde review sluiten",
    reviewSubmitted: "Review verstuurd",
    reviewSubmittedBody: "Je review is binnen. Ga verder naar Atlas Capsule om je nieuwe stempel te zien.",
    continueToAtlasCapsule: "Verder naar Atlas Capsule",
    magicFixTyping: "We typen nu correcties voor grammatica, spelling, interpunctie en hoofdletters. Daarna kun je de verbeterde versie bewerken.",
    magicFixReady: "Je kunt de aanpassingen zien verschijnen en ze daarna accepteren of weigeren.",
    magicFixYourVersion: "Jouw versie",
    magicFixEnhancedVersion: "Verbeterde versie",
    magicFixSuggestedTitle: "Voorgestelde titel",
    magicFixGeneratingTitle: "Titel wordt gemaakt...",
    magicFixAddTitle: "Titel toevoegen",
    magicFixStatusLoading: "OpenAI verbetert je review en maakt een titel...",
    magicFixStatusApplying: "Correcties worden toegepast...",
    magicFixStatusEditable: "Je kunt de titel en review aanpassen voordat je accepteert.",
    magicFixTextareaPlaceholder: "Je review wordt verbeterd...",
    reviewSpeechIntro: "Vertel me over je verblijf bij {property}. Klik op Review opnemen wanneer je klaar bent om te beginnen.",
    followUpSpeechIntro: "Slimme vervolgvraag. {prompt}.",
    nudgeStart: "Begin met wat het meest opviel: de kamer, het personeel, de locatie of het algemene gevoel.",
    nudgeThankYou: "Dank je voor je waardevolle input.",
    yes: "Ja",
    no: "Nee",
    notSure: "Niet zeker",
    propertyFactAmenities: "Reizigers noemen hier het vaakst {items}.",
    propertyFactCheckIn: "De huidige vermelding zegt dat inchecken {value} is.",
    propertyFactCheckOut: "Uitchecken staat vermeld als {value}.",
    propertyFactLatestReview: "De meest recente review in de dataset is vastgelegd op {date}.",
    propertyFactRecentGuest: "Een recente gast zei: {summary}",
    propertyFactRecentSlice: "{count} recente reviews helpen de vervolgvraag te onderbouwen.",
    propertyFactTopGap: "Een van de waardevolste informatiegaten is {label}.",
    propertyFactAnotherGap: "Een ander onderwerp dat mogelijk verouderd is, is {label}.",
    tasteInsight: "Je antwoorden leunden het sterkst naar {leader}, met {runnerUp} vlak daarachter. Dat profiel is precies het soort signaal dat een reisplatform kan gebruiken om toekomstige rangschikkingen te personaliseren en de feiten te tonen die voor jou het belangrijkst zijn.",
    recommendationLeader: "Verblijven met focus op {leader}",
    recommendationRunnerUp: "Topkeuzes voor {runnerUp}",
    recommendationFresh: "Recent bijgewerkte vermeldingen",
    tasteValue: "Waarde",
    tasteValueArchetype: "Optimaliseerder",
    tasteLocation: "Locatie",
    tasteLocationArchetype: "Ontdekker",
    tasteComfort: "Comfort",
    tasteComfortArchetype: "Nester",
    tasteService: "Service",
    tasteServiceArchetype: "Loyalist",
    tasteAmenities: "Voorzieningen",
    tasteAmenitiesArchetype: "Genieter",
    stampediaCapsule: "Capsule",
    travelCapsule: "{name}s reiscapsule",
    travelCapsuleSub: "Beoordeelde verblijven, bewaard als herinneringen",
    dateRange: "Datumbereik",
    duration: "Duur",
    country: "Land",
    stamped: "Gestempeld",
    stampediaPage: "Pagina {page}",
    closeReviewPreview: "Reviewvoorbeeld sluiten",
    savedReview: "Opgeslagen review",
    noStampsYetNote: "Nog geen stempels. Verstuur de eerste review in {title} om dit dagboek te starten.",
    newStampNote: "{property} is zojuist in je {title}-pagina geschoven.",
    stampsCollectedNote: "{count} verzameld voor {country}.",
    openSavedReviewAria: "Opgeslagen review openen voor {property}",
    atlasCapsuleJournal: "Atlas Capsule-journal",
    noStampsYetCountry: "Nog geen stempels",
    firstReviewSubtitle: "Verstuur je eerste review om stempels te gaan verzamelen.",
    countryJournal: "{country}-journal",
    recentStay: "Recente reis",
    qualityLabel: "{count} recente verblijven"
  }
};

export const MAGIC_FIX_COPY_BY_LANGUAGE: Record<string, MagicFixCopy> = {
  en: {
    title: "We enhanced your review.",
    body: "We only fixed grammar, spelling, capitalization, and punctuation without changing what you meant.",
    accept: "Accept",
    keep: "Decline",
    loading: "OpenAI is enhancing your review..."
  },
  es: {
    title: "Mejoramos tu reseña.",
    body: "Solo corregimos gramática, ortografía, mayúsculas y puntuación sin cambiar lo que quisiste decir.",
    accept: "Aceptar",
    keep: "Rechazar",
    loading: "OpenAI está mejorando tu reseña..."
  },
  fr: {
    title: "Nous avons amélioré votre avis.",
    body: "Nous n’avons corrigé que la grammaire, l’orthographe, les majuscules et la ponctuation sans changer votre intention.",
    accept: "Accepter",
    keep: "Refuser",
    loading: "OpenAI améliore votre avis..."
  },
  de: {
    title: "Wir haben deine Bewertung verbessert.",
    body: "Wir haben nur Grammatik, Rechtschreibung, Großschreibung und Zeichensetzung korrigiert, ohne deine Aussage zu ändern.",
    accept: "Annehmen",
    keep: "Ablehnen",
    loading: "OpenAI verbessert deine Bewertung..."
  },
  it: {
    title: "Abbiamo migliorato la tua recensione.",
    body: "Abbiamo corretto solo grammatica, ortografia, maiuscole e punteggiatura senza cambiare ciò che intendevi dire.",
    accept: "Accetta",
    keep: "Rifiuta",
    loading: "OpenAI sta migliorando la tua recensione..."
  },
  pt: {
    title: "Nós aprimoramos sua avaliação.",
    body: "Corrigimos apenas gramática, ortografia, capitalização e pontuação sem mudar o que você quis dizer.",
    accept: "Aceitar",
    keep: "Recusar",
    loading: "A OpenAI está aprimorando sua avaliação..."
  },
  ja: {
    title: "レビューを整えました。",
    body: "意味は変えずに、文法、スペル、句読点、大文字だけを直しました。",
    accept: "承認",
    keep: "辞退",
    loading: "OpenAI がレビューを整えています..."
  },
  zh: {
    title: "我们已优化你的点评。",
    body: "我们只修正了语法、拼写、大小写和标点，不会改变你的原意。",
    accept: "接受",
    keep: "拒绝",
    loading: "OpenAI 正在优化你的点评..."
  },
  ar: {
    title: "لقد حسّنا مراجعتك.",
    body: "قمنا فقط بتصحيح القواعد والإملاء وعلامات الترقيم والحروف الكبيرة من دون تغيير المعنى الذي قصدته.",
    accept: "قبول",
    keep: "رفض",
    loading: "تعمل OpenAI على تحسين مراجعتك..."
  },
  hi: {
    title: "हमने आपका रिव्यू बेहतर किया है।",
    body: "हमने केवल व्याकरण, वर्तनी, कैपिटलाइज़ेशन और विराम चिह्न ठीक किए हैं, अर्थ नहीं बदला है।",
    accept: "स्वीकार करें",
    keep: "अस्वीकार करें",
    loading: "OpenAI आपके रिव्यू को बेहतर कर रहा है..."
  },
  nl: {
    title: "We hebben je review verbeterd.",
    body: "We hebben alleen grammatica, spelling, hoofdletters en leestekens aangepast zonder je betekenis te veranderen.",
    accept: "Accepteren",
    keep: "Afwijzen",
    loading: "OpenAI verbetert je review..."
  }
};

export function formatUiCopy(template: string, values: Record<string, string | number>) {
  return replaceTokens(template, values);
}

export function getReviewIqUiCopy(languageCode: string) {
  return UI_COPY_BY_LANGUAGE[languageCode] ?? UI_COPY_BY_LANGUAGE.en;
}

export function getMagicFixCopy(languageCode: string) {
  return MAGIC_FIX_COPY_BY_LANGUAGE[languageCode] ?? MAGIC_FIX_COPY_BY_LANGUAGE.en;
}
